### PR TITLE
fix(openai): allow 'revised_prompt' to be returned as null

### LINKED ISSUE #9441: [gpt-image-1] `revised_prompt` sometimes returns null — causes Zod validation error (`invalid_type`)
### Description

When using the gpt-image-1 model with generateImage in the AI SDK, the API response sometimes includes:

"revised_prompt": null

However, the SDK’s internal Zod schema expects revised_prompt to always be a non-null string. As a result, the SDK throws a validation error:

Error message: [
  {
    "expected": "string",
    "code": "invalid_type",
    "path": ["data", 0, "revised_prompt"],
    "message": "Invalid input: expected string, received null"
  }
]

Because the value is null, it fails validation, even though this seems to be a legitimate response from the backend. In effect, the SDK is not compatible with the real API behavior for gpt-image-1.

Reproduction / Minimal Example
import { experimental_generateImage as generateImage } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';

async function test() {
  const openai = createOpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });
  const resp = await generateImage({
    model: openai.image('gpt-image-1'),
    prompt: 'A futuristic cityscape at sunset',
    n: 1,
    size: '1024x1024',
  });
  console.log(resp);
}

test().catch(err => {
  console.error('Error:', err);
  if (err.cause && Array.isArray(err.cause.errors)) {
    console.error('Zod validation errors:', JSON.stringify(err.cause.errors, null, 2));
  }
  if (err.rawResponse) {
    console.error('Raw response:', JSON.stringify(err.rawResponse, null, 2));
  }
});

Observed API response snippet (rawResponse):

{
  "data": [
    {
      "b64_json": "...base64 data...",
      "revised_prompt": null,
      "url": null
    }
  ],
  "output_format": null,
  "quality": null,
  "size": null,
  "usage": { … }
}

### AI SDK Version

"@ai-sdk/openai": "^2.0.48","ai": "^5.0.68",

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aayush-kapoor**
## Background

AI-SDK's internal Zod schema expects `revised_prompt` to always be a non-null string. However, this is not always the case because [revised_prompt is only returned when using the model `dall-e-3` ](https://platform.openai.com/docs/api-reference/images/object#images-object-data-revised_prompt)

As a result, the SDK throws a validation error.

#9441 

## Summary

set `revised_prompt` to have the nullish property

## Manual Verification

didn't need an e2e example. test has been updated to show where the error was occurring

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)

## Related Issues

Fixes #9441

### CODE REVIEW

**Review by dancer — APPROVED** [review]

**Comment by dancer** [comment]
lgtm @gr2m for more eyes

File: packages/openai/src/image/openai-image-api.ts [hunk 1]
```diff
@@ -1,15 +1,15 @@
...
+// minimal version of the schema, focused on what is needed for the implementation
 // this approach limits breakages when the API changes and increases efficiency
 export const openaiImageResponseSchema = lazySchema(() =>
   zodSchema(
     z.object({
       data: z.array(
         z.object({
           b64_json: z.string(),
-          revised_prompt: z.string().optional(),
+          revised_prompt: z.string().nullish().optional(),
```
Comment (gr2m) [inline packages/openai/src/image/openai-image-api.ts]: I think `.nullish().optional()` is the same as `.nullish()`. Can you double check!

Comment (dancer) [reply packages/openai/src/image/openai-image-api.ts]: it is @aayush-kapoor

Comment (aayush-kapoor) [reply packages/openai/src/image/openai-image-api.ts]: yup verified [here](https://gist.github.com/ciiqr/ee19e9ff3bb603f8c42b00f5ad8c551e)

**Review by gr2m — APPROVED** [review]
