### PR TITLE
fix(ai): skip tool validation for terminal states when schema is missing

### LINKED ISSUE #13544: TypeValidationError on historical tool parts when tool schema no longer registered
## Description

`createAgentUIStreamResponse` throws `TypeValidationError` ("No tool schema found for tool part X") when message history contains tool parts from tools that are no longer registered (e.g. MCP server disconnected between turns).

The validation fails immediately at the schema lookup — before checking the part's state. Tool parts in terminal states (`output-error`, `output-available`) don't need schema validation; they already executed and their results are stored.

## Reproduction

1. Connect an MCP server → LLM calls MCP tools → tools complete with `output-error` or `output-available`
2. MCP server disconnects (or fails) → tool schemas are no longer registered
3. User sends next message → `createAgentUIStreamResponse` validates all historical message parts
4. Throws: `TypeValidationError: No tool schema found for tool part find_organizations`

## Current behavior

```javascript
// ai/src/...
const tool2 = tools[toolName];
if (!tool2) {
  return {
    success: false,
    error: new TypeValidationError({
      value: toolPart.input,
      cause: `No tool schema found for tool part ${toolName}`,
      ...
    })
  };
}
```

Fails immediately when tool isn't in the map, regardless of part state.

## Expected behavior

Tool parts in terminal states (`output-error`, `output-available`, `output-denied`) should skip schema validation when the tool is no longer registered. The tool already ran — validation serves no purpose and breaks conversations with ephemeral tool sources (MCP servers, dynamic tools).

## Suggested fix

```javascript
const tool2 = tools[toolName];
if (!tool2) {
  // Skip validation for completed tool parts — schema is only needed for pending execution
  const terminalStates = ['output-available', 'output-error', 'output-denied'];
  if (terminalStates.includes(toolPart.state)) {
    continue; // or break out of validation for this part
  }
  return { success: false, error: new TypeValidationError(...) };
}
```

## Environment

- `ai` version: 6.0.115
- `@cloudflare/ai-chat` version: 0.1.8
- Runtime: Cloudflare Workers

## Additional context

This is particularly common with MCP servers which are ephemeral — they can disconnect, fail, or be removed between conversation turns. The conversation history legitimately contains tool parts from servers that no longer exist.

### PR DESCRIPTION
**Pull request by dancer**
## background

when an MCP server disconnects between conversation turns, tool schemas are no longer registered. `validateUIMessages` throws `TypeValidationError` ("No tool schema found for tool part X") on historical tool parts that already completed, permanently bricking the conversation. this is common with ephemeral tool sources like MCP servers and dynamic tools

## summary

- skip validation for tool parts in terminal states (`output-available`, `output-error`, `output-denied`) when the tool schema is no longer registered
- non-terminal states still error as before

## checklist

- [x] tests have been added / updated (for bug fixes / features)
- [ ] documentation has been added / updated (for bug fixes / features)
- [x] a _patch_ changeset for relevant packages has been added (run `pnpm changeset` in root)
- [x] i have reviewed this pull request (self-review)

## related issues

fixes #13544

### CODE REVIEW

File: packages/ai/src/ui/validate-ui-messages.ts [hunk 1]
```diff
@@ -416,6 +416,15 @@ export async function safeValidateUIMessages<UI_MESSAGE extends UIMessage>({
...
 
+            if (
+              !tool &&
+              (toolPart.state === 'output-available' ||
+                toolPart.state === 'output-error' ||
+                toolPart.state === 'output-denied')
+            ) {
+              continue;
+            }
+
```
Comment (lgrammel) [inline packages/ai/src/ui/validate-ui-messages.ts:426]: please add test for this case

**Comment by rossanodr** [comment]
pleaase, aprove it

File: packages/ai/src/ui/validate-ui-messages.ts (hunk 1 above)
Comment (gr2m) [reply packages/ai/src/ui/validate-ui-messages.ts:426]: 9aecc53bf3a95e067813a9421cbcd1cc96d0992a

**Review by gr2m — APPROVED** [review]

**Comment by ghost** [comment]
✅ Backport PR created: https://github.com/vercel/ai/pull/14610
