### PR TITLE
fix: langchain stream not closing

### LINKED ISSUE #97: Stream never closes with LangChainStream using postman
Have a few issues with LangChainStream:

1. Appears stream never closes when API is called
2. Tokens are not getting set or sent down stream, but are coming through when adding callback functions to LangChainStream

Example code: 
```typescript
import { ChatAnthropic } from "langchain/chat_models/anthropic";
import { ChatOpenAI } from 'langchain/chat_models/openai';

import { BaseChatMessage } from "langchain/dist/schema";
import {
  ChatPromptTemplate,
  HumanMessagePromptTemplate,
  PromptTemplate,
  SystemMessagePromptTemplate,
} from "langchain/prompts";
import { StreamingTextResponse, LangChainStream } from "ai";
import { CallbackManager } from "langchain/callbacks";

export const runtime = "edge";

if (!process.env.ANTHROPIC_API_KEY) {
  throw new Error("Missing env var from Anthropic");
}

const createSummaryPrompt = async (
  persona: string,
  preprocessed_data: string
): Promise<BaseChatMessage[]> => {
  const chatPrompt = PromptTemplate.fromTemplate(
      `This is your title: {title}. blah blah blah. \User Data: {userData}.`
);

  const formattedPrompt = await chatPrompt.formatPromptValue({
    persona,
    transcriptData: JSON.stringify(preprocessed_data),
  });

  return formattedPrompt.toChatMessages();
};

export const POST = async (req: Request) => {
  const { title, user_data } =
    (await req.json()) as { title?: string; user_data: string };

  if (!preprocessed_data) {
    return new Response("No transcript in the request", { status: 400 });
  }

  const { stream, handlers } = LangChainStream({
    onStart: async () => console.log("start"),
    onToken: async (token) => console.log(token),
    onCompletion: async () => console.log("end"),
  });

  const llm = new ChatAnthropic({
    apiKey: process.env.ANTHROPIC_API_KEY,
    modelName: "claude-v1.3-100k",
    temperature: 0.1,
    maxTokensToSample: 100000,
    streaming: true,
    verbose: true,
    callbacks: [handlers],
  });

  const prompt = await createSummaryPrompt(persona, preprocessed_data);

  llm
    .call(prompt)
    .then((res) => console.log(stream))
    .catch(console.error).finally(() => console.log("done"));
    
  console.log(stream)
  return new StreamingTextResponse(stream);
};

```

Example cURL:
```
curl --location 'http://localhost:3000/api/generate-summary' \
--header 'Content-Type: text/plain' \
--header 'Cookie: <secret>' \
--data '{"user_data":"blah blah blah","title":"sales chief"}'
```

Postman screenshot - Connection stays open and never ends. No data returns or streams.
image

Console output:
```
start
<ref *1> ReadableStream {
  _state: 'readable',
  _reader: undefined,
  _storedError: undefined,
  _disturbed: false,
  _readableStreamController: ReadableStreamDefaultController {
  _controlledReadableStream: [Circular *1],
  _queue: S {
  _cursor: 0,
  _size: 0,
  _front: { _elements: [], _next: undefined },
  _back: { _elements: [], _next: undefined }
},
  _queueTotalSize: 0,
  _started: true,
  _closeRequested: false,
  _pullAgain: false,
  _pulling: false,
  _strategySizeAlgorithm: [Function],
  _strategyHWM: 0,
  _pullAlgorithm: [Function],
  _cancelAlgorithm: [Function]
}
}
[llm/start] [1:llm:ChatAnthropic] Entering LLM run with input: {
  "messages": [
    [
      {
        "type": "human",
        "data": {
          "content": "redacted",
          "additional_kwargs": {}
        }
      }
    ]
  ]
}
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
token!
[llm/end] [1:llm:ChatAnthropic] [7.56s] Exiting LLM run with output: {
  "generations": [
    [
      {
        "text": "redacted",
        "message": {
          "type": "ai",
          "data": {
            "content": " redacted",
            "additional_kwargs": {}
          }
        }
      }
    ]
  ]
}
<ref *1> ReadableStream {
  _state: 'readable',
  _reader: ReadableStreamDefaultReader {
  _ownerReadableStream: [Circular *1],
  _closedPromise_resolve: [Function],
  _closedPromise_reject: [Function],
  _closedPromise: Promise {
  [Symbol(async_id_symbol)]: 1974,
  [Symbol(trigger_async_id_symbol)]: 0,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined
},
  _readRequests: S {
  _cursor: 77,
  _size: 1,
  _front: {
  _elements: [
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  {
  _chunkSteps: [Function: _chunkSteps],
  _closeSteps: [Function: _closeSteps],
  _errorSteps: [Function: _errorSteps]
}
],
  _next: undefined
},
  _back: {
  _elements: [
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  {
  _chunkSteps: [Function: _chunkSteps],
  _closeSteps: [Function: _closeSteps],
  _errorSteps: [Function: _errorSteps]
}
],
  _next: undefined
}
}
},
  _storedError: undefined,
  _disturbed: true,
  _readableStreamController: ReadableStreamDefaultController {
  _controlledReadableStream: [Circular *1],
  _queue: S {
  _cursor: 0,
  _size: 0,
  _front: { _elements: [], _next: undefined },
  _back: { _elements: [], _next: undefined }
},
  _queueTotalSize: 0,
  _started: true,
  _closeRequested: false,
  _pullAgain: false,
  _pulling: true,
  _strategySizeAlgorithm: [Function],
  _strategyHWM: 0,
  _pullAlgorithm: [Function],
  _cancelAlgorithm: [Function]
}
}
done
token!
token!
token!
token!
token!
token!
done!!!
token!
token!
token!
token!
token!
token!
token!
[llm/end] [1:llm:ChatAnthropic] [8.54s] Exiting LLM run with output: {
  "generations": [
    [
      {
        "text": " redacted",
        "message": {
          "type": "ai",
          "data": {
            "content": " redactedl",
            "additional_kwargs": {}
          }
        }
      }
    ]
  ]
}
<ref *1> ReadableStream {
  _state: 'readable',
  _reader: ReadableStreamDefaultReader {
  _ownerReadableStream: [Circular *1],
  _closedPromise_resolve: [Function],
  _closedPromise_reject: [Function],
  _closedPromise: Promise {
  [Symbol(async_id_symbol)]: 2452,
  [Symbol(trigger_async_id_symbol)]: 2239,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined
},
  _readRequests: S {
  _cursor: 100,
  _size: 1,
  _front: {
  _elements: [
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  {
  _chunkSteps: [Function: _chunkSteps],
  _closeSteps: [Function: _closeSteps],
  _errorSteps: [Function: _errorSteps]
}
],
  _next: undefined
},
  _back: {
  _elements: [
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  {
  _chunkSteps: [Function: _chunkSteps],
  _closeSteps: [Function: _closeSteps],
  _errorSteps: [Function: _errorSteps]
}
],
  _next: undefined
}
}
},
  _storedError: undefined,
  _disturbed: true,
  _readableStreamController: ReadableStreamDefaultController {
  _controlledReadableStream: [Circular *1],
  _queue: S {
  _cursor: 0,
  _size: 0,
  _front: { _elements: [], _next: undefined },
  _back: { _elements: [], _next: undefined }
},
  _queueTotalSize: 0,
  _started: true,
  _closeRequested: false,
  _pullAgain: false,
  _pulling: true,
  _strategySizeAlgorithm: [Function],
  _strategyHWM: 0,
  _pullAlgorithm: [Function],
  _cancelAlgorithm: [Function]
}
}
done
```

Something isn't connecting here I guess if we're getting an array of `undefined`. Any ideas where I'm going wrong here? Any help much appreciated! 

( additional side note: Would be so cool to have a useStream() for features that are not chat and are not completions! e.g. one off API calls formed from app data like mine. I am passing things to useChat({body: {title:, user_data}}) )

### PR DESCRIPTION
**Pull request by aranlucas**
fixes: https://github.com/vercel-labs/ai/issues/97

## The problem
1. Streaming handlers should be used in Request callbacks - https://js.langchain.com/docs/production/callbacks/#when-do-you-want-to-use-each-of-these
2. You can have multiple chains. You need to know when all the chains before closing the stream. Currently, the stream is being closed after the first chain End

## Solution
1. Update docs to reflect request callbaks
2. Add internal state that keeps track of all of the runs happening. If there are no runs, then the stream is safe to close.

### CODE REVIEW

**Review by MaxLeiter — APPROVED** [review]
Thank you! Feel free to open an issue here for tracking the langchain discussion

**Comment by MaxLeiter** [comment]
Actually, I just remembered why @jaredpalmer made the change. Here's the initial issue: https://github.com/vercel-labs/ai/issues/63

It seems like we may want to let the consumer choose which callback to end on, as it's model dependent

**Comment by aranlucas** [comment]
Yeah I figured that was the reasoning, thanks for confirming.

This change will probably break `SequentialChain` use case.

It seems like your suggestion might be the best one. Or langchainjs can expose have something like `handleEnd` where it doesn't depend on a model.

**Comment by aranlucas** [comment]
Last one here before I create an issue: https://js.langchain.com/docs/production/callbacks/#multiple-handlers

Before
````javascript
  const { stream, handlers } = LangChainStream()
 
  const llm = new ChatOpenAI({
    streaming: true,
    callbackManager: CallbackManager.fromHandlers(handlers)
  })
 
  llm
    .call(
      (messages as Message[]).map(m =>
        m.role == 'user'
          ? new HumanChatMessage(m.content)
          : new AIChatMessage(m.content)
      )
    )
    .catch(console.error)
 
  return new StreamingTextResponse(stream)
```

After
```javascript
  // Different handlers for llm, agents, chains
  const { stream, llmHandlers, chainHandlers } = LangChainStream()
 
  // Do not pass handlers here
  const llm = new ChatOpenAI({
    streaming: true,
  })
 
  // Pass handlers here instead
  llm
    .call(
      (messages as Message[]).map(m =>
        m.role == 'user'
          ? new HumanChatMessage(m.content)
          : new AIChatMessage(m.content)
      )
    ,[llmHandlers])
    .catch(console.error)
 
  return new StreamingTextResponse(stream)
```

Reference: https://js.langchain.com/docs/production/callbacks/#multiple-handlers

**Comment by aranlucas** [comment]
Created https://github.com/vercel-labs/ai/issues/205 for further discussions

This PR will probably break the linked usecase - can be closed or left until we find something.

**Comment by jaredpalmer** [comment]
Big fan of `const { stream, llmHandlers, chainHandlers } = LangChainStream()`

**Comment by aranlucas** [comment]
@jaredpalmer that actually won't work after doing some research https://github.com/vercel-labs/ai/issues/205

As an exaggerated example, a chain can spawn a chain that spawns a chain, meaning that on the first chainEnd, the stream will close. You need to be able to count how many things are running

I'm leaning towards https://github.com/vercel-labs/ai/issues/205#issuecomment-1603411125 as the solution now.

**Comment by aranlucas** [comment]
Updated with my latest findings 👀

**Comment by aranlucas** [comment]
Take https://github.com/vercel-labs/ai/issues/205#issuecomment-1603437504 as an example. Let's say we wanted to stream both the responses.

in first chain

```
Tragedy at Sunset on the Beach is a story of love, loss, and redemption. It follows the story of two young lovers, Jack and Jill, who meet on a beach at sunset. They quickly fall in love and plan to spend the rest of their lives together. \n\nHowever, tragedy strikes when Jack is killed in a car accident. Jill is left devastated and unable to cope with the loss of her beloved. She spirals into a deep depression and begins to lose hope. \n\nJust when all seems lost, Jill discovers that Jack had left her a letter before his death. In the letter, he tells her that he will always love her and that she should never give up hope. With this newfound strength, Jill is able to find the courage to move on with her life and find happiness again. \n\nTragedy at Sunset on the Beach is a story of love, loss, and redemption. It is a story of hope and courage in the face of tragedy. It is a story of finding strength in the darkest of times and of never giving up.",     
```

handleChainEnd gets called, stream is closed. Second chain can't write the second response

```
Tragedy at Sunset on the Beach is a powerful and moving story of love, loss, and redemption. The play follows the story of two young lovers, Jack and Jill, whose plans for a future together are tragically cut short when Jack is killed in a car accident. \n\nThe play is beautifully written and the performances are outstanding. The actors bring a depth of emotion to their characters that is both heartbreaking and inspiring. The story is full of unexpected twists and turns, and the audience is taken on an emotional rollercoaster as Jill struggles to come to terms with her loss. \n\nThe play is ultimately a story of hope and resilience, and it is sure to leave audiences with a newfound appreciation for life and love. Tragedy at Sunset on the Beach is a must-see for anyone looking for an emotionally charged and thought-provoking experience."
```

There's probably many ways to fix this, but the way I suggested in this PR seems to work for most use cases I've tried.

File: packages/core/streams/langchain-stream.ts [hunk 1]
```diff
@@ -3,20 +3,77 @@ import { type AIStreamCallbacks, createCallbacksTransformer } from './ai-stream'
...
+      handleToolEnd: async (_output: string, runId: string) => {
+        await handleEnd(runId)
+      },
+      handleToolError: async (e: Error, runId: string) => {
+        await handleError(e, runId)
+      },
+      handleAgentAction: async (_action: any, runId: string) => {
+        handleStart(runId)
+      },
+      handleAgentEnd: async (_output: any, runId: string) => {
```
Comment (nfcampos) [inline packages/core/streams/langchain-stream.ts:75]: You should remove this one, as an agent is a chain, so handleChainEnd will be called for agent runs too

File: packages/core/streams/langchain-stream.ts [hunk 2]
```diff
@@ -3,20 +3,77 @@ import { type AIStreamCallbacks, createCallbacksTransformer } from './ai-stream'
...
+        handleStart(runId)
+      },
+      handleToolEnd: async (_output: string, runId: string) => {
+        await handleEnd(runId)
+      },
+      handleToolError: async (e: Error, runId: string) => {
+        await handleError(e, runId)
+      },
+      handleAgentAction: async (_action: any, runId: string) => {
+        handleStart(runId)
```
Comment (nfcampos) [inline packages/core/streams/langchain-stream.ts:73]: You should remove this one, as this is not a start event (agents are chains, their start/end events are those of chains

File: packages/core/streams/langchain-stream.ts [hunk 3]
```diff
@@ -3,20 +3,77 @@ import { type AIStreamCallbacks, createCallbacksTransformer } from './ai-stream'
...
+        await handleError(e, runId)
+      },
+      handleChatModelStart: async (
+        _llm: any,
+        _messages: any,
+        runId: string
+      ) => {
+        handleStart(runId)
+      },
+      handleChatModelEnd: async (_output: any, runId: string) => {
```
Comment (nfcampos) [inline packages/core/streams/langchain-stream.ts:51]: This callback event does not exist (currently), handleLLMEnd is used by chat models

File: packages/core/streams/langchain-stream.ts [hunk 4]
```diff
@@ -3,20 +3,77 @@ import { type AIStreamCallbacks, createCallbacksTransformer } from './ai-stream'
 export function LangChainStream(callbacks?: AIStreamCallbacks) {
   const stream = new TransformStream()
   const writer = stream.writable.getWriter()
+
+  const runs = new Set()
+
+  const handleError = async (e: Error, runId: string) => {
+    runs.delete(runId)
```
Comment (nfcampos) [inline packages/core/streams/langchain-stream.ts:10]:
```suggestion
    await handleEnd(runId)
```

File: packages/core/streams/langchain-stream.ts [hunk 5]
```diff
@@ -3,20 +3,77 @@ import { type AIStreamCallbacks, createCallbacksTransformer } from './ai-stream'
...
+    await writer.ready
+    await writer.abort(e)
```
Comment (nfcampos) [inline packages/core/streams/langchain-stream.ts:12]: You might want to be careful with this one, in some chains that eg run multiple things in parallel there could be other events arriving after an error event, it doesn't look like you're handling those

Comment (aranlucas) [reply packages/core/streams/langchain-stream.ts:12]: How should it be handled? If there's an error, can it recover gracefully from it?

Right now this is definitely giving up on first error, but I'll be honest I haven't encountered a scenario where the error was recovered and it could continue the chain.

Comment (nfcampos) [reply packages/core/streams/langchain-stream.ts:12]: So it will overall be cancelled when the first error occurs. The issue is if it's a chain with multiple LLM calls in parallel you may still receive new tokens from call #2 after call #1 has failed. In which case currently what would happen is it would probably throw an exception in handleLLMNewToken as you try to write to an already aborted writer?

Comment (aranlucas) [reply packages/core/streams/langchain-stream.ts:12]: Note: the exception of writing to a stream in closed state seems to be handled somewhere that doesn't seem to cause catastrophic errors.

Comment (nfcampos) [reply packages/core/streams/langchain-stream.ts:12]: Yes any exceptions inside a callback handler are caught by langchain to avoid an error in a callback handler interrupting a run

Comment (aranlucas) [reply packages/core/streams/langchain-stream.ts:12]: Ok I see your point. 

How does this suggestion sound. 

Keep an error state handler

```javascropt
let errors = []
```

Whenever we encounter an error on any handle*Error push it errors

Then `handleEnd`

```javascript
  const handleEnd = async (runId: string) => {
    runs.delete(runId)

    if (runs.size === 0) {
      if (error.length !=0) {
          await writer.ready
          await writer.abort(e)
          return;
      }
      await writer.ready
      await writer.close()
    }
  }
```

Comment (aranlucas) [reply packages/core/streams/langchain-stream.ts:12]: Or I can just re-throw the error similar to https://github.com/vercel-labs/ai/blob/main/packages/core/streams/ai-stream.ts#L152-L154

 I think an issue I had yesterday working with this is that even  though the stream had ended, the background processing had not stopped. This led me to have to restart dev server to clear out running processes

Comment (MaxLeiter) [reply packages/core/streams/langchain-stream.ts:12]: I'm a fan of rethrowing the error

**Comment by jaredpalmer** [comment]
Are we good to merge @nfcampos @MaxLeiter ?

**Review by nfcampos — APPROVED** [review]

**Comment by nfcampos** [comment]
looks good to me

File: docs/pages/docs/guides/langchain.mdx [hunk 6]
```diff
@@ -34,6 +34,7 @@ export async function POST(req: Request) {
           ? new HumanChatMessage(m.content)
           : new AIChatMessage(m.content)
       ),
+      [],
```
[the remark this answers is not in the document]
Comment (nfcampos) [reply docs/pages/docs/guides/langchain.mdx:37]: I think that should be `undefined`

[the remark this answers is not in the document]
Comment (jaredpalmer) [reply docs/pages/docs/guides/langchain.mdx]: stylistic suggestion: y'all should have only a two arguments to `.call`, passing `undefined` is very odd.

**Comment by aranlucas** [comment]
🙏

File: docs/pages/docs/guides/langchain.mdx (hunk 6 above)
[the remark this answers is not in the document]
Comment (nfcampos) [reply docs/pages/docs/guides/langchain.mdx]: Yep agreed, I've improved this here https://github.com/hwchase17/langchainjs/pull/1868 once that is merged you'll be able to do instead `llm.call(messages, { callbacks: handlers })`
