### PR TITLE
fix(google-vertex): allow 'vertex' as a key for providerOptions

### LINKED ISSUE #7783: Unexpected behavior when passing providerOptions to vertex/google provider
### Description

The chat model is imported from google (`GoogleGenerativeAILanguageModel`) so it looks for the `google` provider. When doing this from vertex it is kind of weird. For example when using `GoogleVertexImageModel` it does look for the `vertex` provider in the providerOptions

### AI SDK Version

- ai: 5.0.2

### PR DESCRIPTION
**Pull request by aayush-kapoor**
## Background

#7783

When providerOptions are defined in the vertex provider with the key `vertex`, they are ignored and not sent in the request to the model; they only work with `google` key. 

## Summary

Allow the `vertex` to be a valid key for setting providerOptions for vertex provider for consistency sake

## Manual Verification

test cases added

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)

## Future Work

Need to add codemods for the changes in the migration guide

## Related Issues 

Fixes #7783

### CODE REVIEW

File: examples/ai-core/src/generate-text/google-vertex-safety.ts [hunk 1]
```diff
@@ -4,9 +4,9 @@ import 'dotenv/config';
 
 async function main() {
   const result = await generateText({
-    model: vertex('gemini-1.5-pro'),
+    model: vertex('gemini-2.5-flash'),
     providerOptions: {
-      google: {
+      vertex: {
```
Comment (lgrammel) [inline examples/ai-core/src/generate-text/google-vertex-safety.ts:9]: will this be a breaking change? if so we need to limit to ai sdk 6 and add it to the migration guide (and potentially add a codemod)

File: packages/google-vertex/src/google-vertex-provider.ts [hunk 2]
```diff
@@ -140,6 +140,7 @@ export function createVertex(
           /^gs:\/\/.*$/,
         ],
       }),
+      providerOptionsName: 'vertex',
```
Comment (lgrammel) [inline packages/google-vertex/src/google-vertex-provider.ts]: does this also affect `providerMetadata` (it should because we automatically mv metadata to options) - so the property name should be rename to providerName (which may already exist)

File: packages/google/src/google-generative-ai-language-model.ts [hunk 3]
```diff
@@ -47,6 +47,12 @@ type GoogleGenerativeAIConfig = {
    * The supported URLs for the model.
    */
   supportedUrls?: () => LanguageModelV3['supportedUrls'];
+
+  /**
+   * This allows Vertex to use 'vertex' as the primary provider options key
+   * while maintaining backward compatibility with 'google'.
+   */
+  providerOptionsName?: string;
```
Comment (lgrammel) [inline packages/google/src/google-generative-ai-language-model.ts]: extract from `provider` string instead (there are examples eg openai compat afaik)

File: packages/google/src/google-generative-ai-language-model.ts [hunk 4]
```diff
@@ -91,11 +97,22 @@ export class GoogleGenerativeAILanguageModel implements LanguageModelV3 {
...
+        })
+      : undefined;
+
+    if (googleOptions == null) {
+      googleOptions = await parseProviderOptions({
+        provider: 'google',
+        providerOptions,
+        schema: googleGenerativeAIProviderOptions,
+      });
+    }
```
Comment (lgrammel) [inline packages/google/src/google-generative-ai-language-model.ts]: need to change metadata as well

Comment (lgrammel) [reply packages/google/src/google-generative-ai-language-model.ts]: providerName should always be available, no conditional handling needed

File: packages/google/src/google-generative-ai-language-model.ts (hunk 3 above)
Comment (aayush-kapoor) [reply packages/google/src/google-generative-ai-language-model.ts]: done

File: packages/google-vertex/src/google-vertex-provider.ts (hunk 2 above)
Comment (aayush-kapoor) [reply packages/google-vertex/src/google-vertex-provider.ts]: changed for `providerMetadata` as well

File: packages/google/src/google-generative-ai-language-model.ts [hunk 5]
```diff
@@ -94,12 +94,23 @@ export class GoogleGenerativeAILanguageModel implements LanguageModelV3 {
   }: Parameters<LanguageModelV3['doGenerate']>[0]) {
     const warnings: SharedV3Warning[] = [];
 
-    const googleOptions = await parseProviderOptions({
-      provider: 'google',
+    const providerOptionsName = this.config.provider.includes('vertex')
+      ? 'vertex'
+      : 'google';
```
Comment (lgrammel) [inline packages/google/src/google-generative-ai-language-model.ts:99]: can extraction code similar to openai compatible be used here?

Comment (lgrammel) [reply packages/google/src/google-generative-ai-language-model.ts:99]: or is this challenging bc of `   provider: `google.vertex.${name}`,`?

Comment (lgrammel) [reply packages/google/src/google-generative-ai-language-model.ts:99]: (then might be fine as is but google.vertex is a problem bc it is different from our standard convention)

**Comment by lgrammel** [comment]
Please add to migration guide. Are any changes to the google vertex provider docs necessary?

**Review by lgrammel — APPROVED** [review]

File: packages/google/src/google-generative-ai-language-model.ts (hunk 5 above)
Comment (aayush-kapoor) [reply packages/google/src/google-generative-ai-language-model.ts:99]: i actually didn't refer to the openai compat code. do you think i still should?

Comment (aayush-kapoor) [reply packages/google/src/google-generative-ai-language-model.ts:99]: i think the current method works; extracting from provider via splitting could become problematic.

**Comment by aayush-kapoor** [comment]
added a migration guide - will be adding codemods in a follow up PR once this lands
