### PR TITLE
fix(@ai-sdk/google): convert array types to anyOf for gemini compatability

### LINKED ISSUE #10121: fix(@ai-sdk/google): Union types in tool schemas cause invalid JSON payload error
### Bug Report

**Description:**
When using `z.union()` types in a tool's input schema with Google's Gemini model, the SDK generates an invalid JSON payload that Google's API rejects with a "Proto field is not repeating, cannot start list" error.

**Steps to Reproduce:**
1. Create a tool with a union type parameter:
```typescript
calculate: tool({
  description: 'Perform a calculation',
  inputSchema: z.object({
    value: z.union([z.string(), z.number()]),
    operation: z.enum(['double', 'triple']),
  }),
  execute: async ({ value, operation }) => { /* ... */ },
})
```
2. Use the tool with `streamText()` and Google's Gemini model
3. Trigger the tool by sending a message like "double 3"

**Expected Behavior:**
The tool should execute successfully with either string or number input.

**Actual Behavior:**
API returns 400 error:
```
Invalid JSON payload received. Unknown name "type" at 'tools.function_declarations[1].parameters.properties[0].value': Proto field is not repeating, cannot start list.
```

**Error Details:**
- Error occurs at: `tools.function_declarations[1].parameters.properties[0].value`
- Status Code: 400
- Model: `gemini-2.5-flash`

**Environment:**
- AI SDK version: 5.0.90
- Node.js version: v22
- Package: `@ai-sdk/google`

**Additional Context:**

---

The full example code for reproducing the error:

```typescript
import { google } from '@ai-sdk/google';
import { stepCountIs, ModelMessage, streamText, tool } from 'ai';
import 'dotenv/config';
import * as readline from 'node:readline/promises';
import { z } from 'zod';

const terminal = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const messages: ModelMessage[] = [];

async function main() {
  while (true) {
    messages.push({ role: 'user', content: await terminal.question('You: ') });

    const result = streamText({
      model: google('gemini-2.5-flash'),
      tools: {
        weather: tool({
          description: 'Get the weather in a location',
          inputSchema: z.object({
            location: z
              .string()
              .describe('The location to get the weather for'),
          }),
          execute: async ({ location }) => ({
            location,
            temperature: 72 + Math.floor(Math.random() * 21) - 10,
          }),
        }),
        // Test tool with multiple types (tests the anyOf conversion fix)
        calculate: tool({
          description:
            'Perform a calculation with a value that can be string or number',
          inputSchema: z.object({
            value: z
              .union([z.string(), z.number()])
              .describe('A value that can be either a string or a number'),
            operation: z
              .enum(['double', 'triple'])
              .describe('The operation to perform'),
          }),
          execute: async ({ value, operation }) => {
            console.log('value', value);
            console.log('operation', operation);
            const numValue =
              typeof value === 'string' ? parseFloat(value) : value;
            const multiplier = operation === 'double' ? 2 : 3;
            return {
              input: value,
              result: numValue * multiplier,
              operation,
            };
          },
        }),
      },
      stopWhen: stepCountIs(5),
      messages,
    });

    process.stdout.write('\nAssistant: ');
    for await (const delta of result.textStream) {
      process.stdout.write(delta);
    }
    process.stdout.write('\n\n');

    messages.push(...(await result.response).messages);
  }
}

main().catch(console.error);
```

### AI SDK Version

ai: 5.0.90
- @ai-sdk/google: 2.0.30

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wangyedev**
## Background

  The Google provider recently rejected tool schemas with JSON Schema type arrays (e.g., ['string','number']), and Gemini’s API expects tools as an array of tool objects rather
  than a single object. This caused function-calling failures for union-typed tool inputs and mismatched payload shapes.

  ## Summary

  - Convert JSON Schema arrays in type to OpenAPI-compatible anyOf, and extract single-type arrays to a scalar type.
  - Update Google tools payload from an object to an array of tool objects: tools: [{ functionDeclarations } ].
  - Add tests covering:
      - anyOf conversion for multi-type arrays and single-type array extraction.
      - Updated tools request shape expectations in Google language model and prepare-tools tests.
  - Example: switch to google('gemini-2.5-flash') and add a union-typed calculate tool to exercise the anyOf conversion.

  ## Manual Verification

  - Ran @ai-sdk/google test suites (Node and Edge) to cover tool preparation, request payload structure, and schema conversion:
      - Command: pnpm --filter @ai-sdk/google test
      - Result: 165 tests across 9 files passed.
  - Sanity-checked the example examples/ai-core/src/stream-text/google-chatbot.ts to ensure:
      - Tool with z.union([z.string(), z.number()]) compiles and produces a schema accepted by the Google adapter.
      - Request building uses tools as an array.

  ## Checklist

  - [x] Tests have been added / updated (for bug fixes / features)
  - [ ] Documentation has been added / updated (for bug fixes / features)
  - [ ] A patch changeset for relevant packages has been added (for bug fixes / features - run pnpm changeset in the project root)
  - [x] I have reviewed this pull request (self-review)

  ## Future Work

  - Audit docs and examples for Google tools shape to ensure consistency with the new array form.
  
## Related Issues

closes  https://github.com/vercel/ai/issues/10121

### CODE REVIEW

File: packages/google/src/convert-json-schema-to-openapi-schema.ts [hunk 1]
```diff
@@ -46,8 +46,15 @@ export function convertJSONSchemaToOpenAPISchema(
...
+      } else if (type.length === 1) {
+        // Single type in array, extract it
+        result.type = type[0];
       } else {
-        result.type = type;
+        // Multiple types: convert to anyOf
+        // Note: anyOf is supported by Gemini API as of November 2025.
+        // Array types (e.g., type: ["string", "number"]) are not supported
+        // by Google's Protocol Buffer API and will cause errors.
+        result.anyOf = type.map(t => ({ type: t }));
```
Comment (gr2m) [inline packages/google/src/convert-json-schema-to-openapi-schema.ts]: Why not always use `anyOf`, even if there is just one item?

Comment (wangyedev) [reply packages/google/src/convert-json-schema-to-openapi-schema.ts]: Makes sense, this part could be simplified. Thanks for pointing it out!

**Review by gr2m — APPROVED** [review]
I confirmed the example was failing on `main` with the prompt "tripple two", and it worked with your fix. Thank you Ye! Congratulations to your first contribution to the AI SDK!
