### PR TITLE
fix(ai): pass providerMetadata in smooth stream

### LINKED ISSUE #11602: [Bug] Anthropic extended thinking: reasoning blocks lost during multi-step tool calls
## Description

When using `streamText` with Anthropic thinking models (e.g., `claude-sonnet-4-20250514`), reasoning content is lost during multi-step tool call workflows.

**Two related issues:**

1. **`response.messages` reasoning parts are missing `providerMetadata` with signatures** - The signature is only available in the separate `reasoning` array, making it impossible to properly reconstruct messages for subsequent turns.

2. **In `onFinish`, reasoning is lost from consolidated `response.messages`** - When using AI SDK's built-in agent loop (`maxSteps`), `onStepFinish` shows reasoning on all turns, but `onFinish` loses 75% of reasoning blocks.

---

## Reproduction

Gist: https://gist.github.com/p3droml/503c5d4888182a75222377109bfdd291

To run:
git clone https://gist.github.com/p3droml/503c5d4888182a75222377109bfdd291.git mre
cd mre && npm install
ANTHROPIC_API_KEY=your-key npx tsx anthropic-thinking-bug.ts

### ProviderMetadata Issue

When extracting reasoning from `response.messages`, the signature is **not included**:

```typescript
// response.messages reasoning part:
{ type: "reasoning", text: "..." }  // NO providerMetadata!

// separate reasoning array:
{ type: "reasoning", text: "...", providerMetadata: { anthropic: { signature: "Esg..." } } }
```

---

### The Pattern Explained

1. **Turn 1**: User message → Model generates thinking + tool call → reasoning present ✅
2. **Turn 2-4**: Tool results sent back → Model processes results without generating NEW thinking → reasoning missing ❌

The model doesn't always generate new thinking blocks when processing tool results. This is expected model behavior. However:

1. **`response.messages` reasoning parts don't include `providerMetadata` with signatures** - making it impossible to properly forward thinking blocks
2. **`onFinish` loses reasoning that was present in `onStepFinish`** - consolidation drops 75% of reasoning

### Anthropic's Requirements

From Anthropic's Extended Thinking Documentation:

> "When thinking is enabled, a final assistant message must start with a thinking block (preceding the lastmost set of tool_use and tool_result blocks). We recommend you include thinking blocks from previous turns."

> "You must include the complete, unmodified thinking or redacted_thinking block back to the API."

---

## Related Issues

- [openai/openai-agents-js#770](https://github.com/openai/openai-agents-js/issues/770) - "Anthropic with reasoning and tool calling fails to send thinking content back up on subsequent turn"
- [vercel/ai#4992](https://github.com/vercel/ai/issues/4992) - `appendResponseMessages` ignores reasoning (fixed in PR #5041)
- [vercel/ai#8823](https://github.com/vercel/ai/issues/8823) - Post-tool reasoning missing from steps
- [vercel/ai#5087](https://github.com/vercel/ai/discussions/5087) - Reasoning promises undefined with streamText

---

## Environment

```
ai: 6.0.16
@ai-sdk/anthropic: 3.0.8
Model: claude-sonnet-4-20250514
Node.js: 22.x
OS: macOS
```

---

## Expected Behavior

1. Reasoning should be preserved and available in `onFinish` for ALL responses
2. The `response.messages` array should include reasoning blocks with `providerMetadata` (signatures)
3. The separate `reasoning` parameter should be consistent with `response.messages`
4. Multi-step tool call workflows should maintain reasoning context throughout

---

## Actual Behavior

1. `response.messages` reasoning parts are missing `providerMetadata` with signatures
2. In `onFinish`, 75% of reasoning is lost (even though `onStepFinish` shows reasoning on all turns)
3. Both `response.messages` and the separate `reasoning` array are empty for turns 2-4

---

## Additional Context

The issue was tested both before and after upgrading from:
- `ai@6.0.3` → `ai@6.0.16`
- `@ai-sdk/anthropic@3.0.1` → `@ai-sdk/anthropic@3.0.8`

The bug persists across versions.

### AI SDK Version

ai: 6.0.16
@ai-sdk/anthropic: 3.0.8
Model: claude-sonnet-4-20250514
Node.js: 22.x
OS: macOS

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #11689: smoothStream strips providerMetadata from reasoning-delta chunks, breaking extended thinking multi-step
When using `streamText` with Anthropic's extended thinking feature and `smoothStream` transform, the thinking signature is lost between steps, causing the API to reject subsequent requests with:

```
messages.1.content.0.type: Expected 'thinking' or 'redacted_thinking', but found 'tool_use'
```

### Root Cause

The `smoothStream` transform in `packages/ai/src/generate-text/smooth-stream.ts` does not preserve `providerMetadata` when processing `reasoning-delta` chunks.

Anthropic sends the thinking signature as a `signature_delta` event, which the `@ai-sdk/anthropic` provider correctly converts to a `reasoning-delta` chunk:

```typescript
{
  type: 'reasoning-delta',
  id: '0',
  delta: '',  // empty text
  providerMetadata: {
    anthropic: {
      signature: 'EtICCkYICxgCKkCs2rGvlzbJBMjJdfgFdTPNfWPhKh5...'
    }
  }
}
```

However, `smoothStream` only preserves `type`, `text`, and `id` when enqueueing chunks:

**Line 115 (flushBuffer):**
```typescript
controller.enqueue({ type, text: buffer, id });  // ❌ No providerMetadata
```

**Line 141 (transform):**
```typescript
controller.enqueue({ type, text: match, id });  // ❌ No providerMetadata
```

This causes the signature to be lost, which means the thinking block cannot be reconstructed for subsequent API calls.

### Steps to Reproduce

1. Create a `streamText` call with Anthropic model using extended thinking:
```typescript
const result = streamText({
  model: anthropic('claude-opus-4-5-20251101'),
  providerOptions: {
    anthropic: {
      thinking: { type: 'enabled', budgetTokens: 10000 }
    }
  },
  tools: { /* some tools */ },
  maxSteps: 5,
  experimental_transform: smoothStream({ delayInMs: 20, chunking: 'word' }),
  messages: [{ role: 'user', content: 'Do something that requires tool use' }]
});
```

2. The first step completes with thinking + tool calls
3. Step 2 fails with the error about missing thinking block

### Expected Behavior

`smoothStream` should preserve `providerMetadata` on all chunks, especially `reasoning-delta` chunks that carry the Anthropic thinking signature.

### Actual Behavior

`providerMetadata` is stripped from `reasoning-delta` chunks, causing the signature to be lost and breaking multi-step extended thinking.

### Workaround

Disable `smoothStream` for agents that use extended thinking:

```typescript
experimental_transform: agentConfig.thinking ? undefined : smoothStream({ ... })
```

### Additional Context

This issue is related to:
- [openai-agents-js #770](https://github.com/openai/openai-agents-js/issues/770) - Similar issue with signature not being captured from reasoning-delta
- [vercel/ai #7729](https://github.com/vercel/ai/issues/7729) - Extended thinking requires thinking block on final message

---

# Suggested Fix (Diff)

```diff
--- a/packages/ai/src/generate-text/smooth-stream.ts
+++ b/packages/ai/src/generate-text/smooth-stream.ts
@@ -106,6 +106,7 @@ export function smoothStream<TOOLS extends ToolSet = ToolSet>(
   return () => {
     let buffer = '';
     let id = '';
+    let providerMetadata: ProviderMetadata | undefined = undefined;
     let type: 'text-delta' | 'reasoning-delta' | undefined = undefined;

     function flushBuffer(
@@ -113,6 +114,7 @@ export function smoothStream<TOOLS extends ToolSet = ToolSet>(
     ) {
       if (buffer.length > 0 && type !== undefined) {
-        controller.enqueue({ type, text: buffer, id });
+        controller.enqueue({ type, text: buffer, id, providerMetadata });
         buffer = '';
       }
     }
@@ -121,6 +123,14 @@ export function smoothStream<TOOLS extends ToolSet = ToolSet>(
       async transform(chunk, controller) {
         // Handle non-smoothable chunks: flush buffer and pass through
         if (chunk.type !== 'text-delta' && chunk.type !== 'reasoning-delta') {
           flushBuffer(controller);
           controller.enqueue(chunk);
           return;
         }

+        // For reasoning-delta with empty text but providerMetadata (e.g., signature),
+        // pass through immediately without buffering
+        if (chunk.type === 'reasoning-delta' && chunk.text === '' && chunk.providerMetadata) {
+          flushBuffer(controller);
+          controller.enqueue(chunk);
+          return;
+        }
+
         // Flush buffer when type or id changes
         if ((chunk.type !== type || chunk.id !== id) && buffer.length > 0) {
           flushBuffer(controller);
         }

         buffer += chunk.text;
         id = chunk.id;
         type = chunk.type;
+        // Capture providerMetadata (signature comes in final reasoning-delta)
+        if (chunk.providerMetadata) {
+          providerMetadata = chunk.providerMetadata;
+        }

         let match;

         while ((match = detectChunk(buffer)) != null) {
-          controller.enqueue({ type, text: match, id });
+          controller.enqueue({ type, text: match, id, providerMetadata });
           buffer = buffer.slice(match.length);
+          // Clear providerMetadata after first enqueue to avoid duplicating
+          providerMetadata = undefined;

           await delay(delayInMs);
         }
       },
     });
   };
 }
```

## Key Changes

1. **Track `providerMetadata`**: Add state variable to capture providerMetadata from chunks
2. **Pass through signature chunks immediately**: Reasoning-delta with empty text but providerMetadata (the signature) should bypass buffering
3. **Include providerMetadata in enqueued chunks**: Both `flushBuffer` and the main transform should include providerMetadata
4. **Clear after use**: Avoid duplicating providerMetadata on subsequent chunks

### AI SDK Version

- `ai`: 6.0.19
- `@ai-sdk/anthropic`: 3.0.9
- Model: `claude-opus-4-5-20251101` with extended thinking enabled

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aayush-kapoor**
## Background

when using anthropic's extended thinking with tool calls, we drop the thinking blocks from previous turns.

#11602 

based on the reproduction provided, the issue turned out to be in smoothStream, where smoothStream was stripping providerMetadata from reasoning-delta chunks. this signature is required when sending thinking blocks back to the API in subsequent turns

## Summary

pass `providerMetadata` through smoothStream

## Manual Verification

the reproduction code [given here](https://gist.github.com/p3droml/503c5d4888182a75222377109bfdd291) was run before and after the fix, and was resolved

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Related Issues

Fixes #11602 and #11689

### CODE REVIEW

File: packages/ai/src/generate-text/smooth-stream.ts [hunk 1]
```diff
@@ -135,6 +143,11 @@ export function smoothStream<TOOLS extends ToolSet>({
         id = chunk.id;
         type = chunk.type;
 
+        // Preserve providerMetadata (e.g., Anthropic thinking signatures)
+        if (chunk.providerMetadata != null) {
+          providerMetadata = chunk.providerMetadata;
+        }
```
Comment (lgrammel) [inline packages/ai/src/generate-text/smooth-stream.ts:149]: do we need some merge algorithm here?

**Review by lgrammel — APPROVED** [review]

File: packages/ai/src/generate-text/smooth-stream.ts (hunk 1 above)
Comment (aayush-kapoor) [reply packages/ai/src/generate-text/smooth-stream.ts:149]: we could do a shallow merge, but that behaviour *may* vary and we could ITG. the solution for now assumes that the provider metadata arrives on a chunk with empty or minimal tex spt,ecifically at the end of a reasoning/text segment.

we can observe behaviour as to what users report and then make changes accordingly

Comment (aayush-kapoor) [reply packages/ai/src/generate-text/smooth-stream.ts:149]: let me know if this is good to merge then
