### PR TITLE
fix(anthropic, amazon-bedrock): migrate output_format to output_config.format

### LINKED ISSUE #12298: Anthropic provider sends deprecated `output_format` instead of `output_config.format`, breaking Bedrock structured outputs
## Description

`@ai-sdk/anthropic` sends the deprecated `output_format` parameter when using `structuredOutputMode: "outputFormat"`. The Anthropic API has migrated to `output_config.format` ([docs](https://platform.claude.com/docs/en/build-with-claude/structured-outputs)).

The direct Anthropic API still accepts `output_format` temporarily, but **Amazon Bedrock already rejects it**:

```
output_format: This field is deprecated. Use 'output_config.format' instead.
See https://platform.claude.com/docs/en/build-with-claude/structured-outputs for more information.
```

This means there is currently **no way** to use structured outputs with thinking/adaptive on Bedrock through the AI SDK, even though the Bedrock API fully supports it via `output_config.format`.

### Root cause

In `@ai-sdk/anthropic`, the request body is built with the deprecated parameter name:

```typescript
// @ai-sdk/anthropic/dist/index.mjs ~line 2599
...useStructuredOutput && responseFormat?.type === "json" && responseFormat.schema != null && {
  output_format: {       // <-- deprecated, should be output_config.format
    type: "json_schema",
    schema: responseFormat.schema
  }
},
```

Additionally, `@ai-sdk/amazon-bedrock/anthropic` hardcodes `supportsNativeStructuredOutput: false` with the comment _"force the use of JSON tool fallback for structured outputs since beta header isn't supported"_ — but structured outputs are now GA on Bedrock (no beta header required).

### Reproduction

Full reproduction script (3 tests — 2 fail via AI SDK, 1 passes via `@anthropic-ai/bedrock-sdk`):
**https://gist.github.com/p3droml/4b9a903054952a1095a71d88ce10ff4e**

```bash
npm install ai @ai-sdk/amazon-bedrock @anthropic-ai/bedrock-sdk zod tsx
# Set AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
npx tsx test-bedrock-structured-output.ts
```

Output:

```
1. AI SDK — bedrock (Converse API)
   ✗ FAILED: Thinking may not be enabled when tool_choice forces tool use.

2. AI SDK — bedrockAnthropic (Invoke API, structuredOutputMode: outputFormat)
   ✗ FAILED: output_format: This field is deprecated. Use 'output_config.format' instead.

3. @anthropic-ai/bedrock-sdk — output_config.format (native SDK)
   Output: { answer: 'Love is a deep emotional bond...' }
   ✓ PASSED
```

### Suggested fix

1. In `@ai-sdk/anthropic`: rename `output_format` to `output_config.format` in the request body
2. In `@ai-sdk/amazon-bedrock/anthropic`: set `supportsNativeStructuredOutput: true` (structured outputs are GA on Bedrock, no beta header needed)

## AI SDK Version

- `ai`: 6.0.72
- `@ai-sdk/anthropic`: 3.0.37
- `@ai-sdk/amazon-bedrock`: 4.0.49
- `@anthropic-ai/bedrock-sdk`: 0.26.3 (used to verify Bedrock API works)

### PR DESCRIPTION
**Pull request by muraliavarma**
## Background

#12298 

## Summary

- **`@ai-sdk/anthropic`**: Migrated the deprecated `output_format` request parameter to `output_config.format`, aligning with the [current Anthropic API](https://platform.claude.com/docs/en/build-with-claude/structured-outputs). The `effort` and `format` fields are now merged into a single `output_config` object to avoid one spread overwriting the other.
- **`@ai-sdk/amazon-bedrock`**: Enabled `supportsNativeStructuredOutput: true` for Bedrock Anthropic models. Structured outputs are now GA on Bedrock and no longer require a beta header, so the JSON tool fallback is no longer necessary.

## Manual Verification

verified the fix by running the following code snippet before and after the changes

<Details> 
<summary> repro </summary>

```ts
import { bedrockAnthropic } from '@ai-sdk/amazon-bedrock/anthropic';
import { generateText, Output } from 'ai';
import 'dotenv/config';
import { z } from 'zod';
import { run } from '../../lib/run';

run(async () => {
  const result = await generateText({
    model: bedrockAnthropic('us.anthropic.claude-opus-4-6-v1'),
    output: Output.object({
      schema: z.object({
        recipe: z.object({
          name: z.string(),
          ingredients: z.array(
            z.object({
              name: z.string(),
              amount: z.string(),
            }),
          ),
          steps: z.array(z.string()),
        }),
      }),
    }),
    providerOptions: {
      anthropic: {
        structuredOutputMode: "outputFormat",
        thinking: { type: "adaptive" },
        effort: "low",
      },
    },
    prompt: 'Generate a lasagna recipe.',
  });

  console.log('Recipe:', JSON.stringify(result.output, null, 2));
  console.log();
  console.log('Finish reason:', result.finishReason);
  console.log('Usage:', result.usage);
});

```
</Details>

## Related Issues

Fixes #12298

### CODE REVIEW

File: packages/amazon-bedrock/src/anthropic/bedrock-anthropic-provider.ts [hunk 1]
```diff
@@ -319,8 +319,8 @@ export function createBedrockAnthropic(
 
       // Bedrock Anthropic doesn't support URL sources, force download and base64 conversion
       supportedUrls: () => ({}),
-      // force the use of JSON tool fallback for structured outputs since beta header isn't supported
-      supportsNativeStructuredOutput: false,
+      // native structured output via output_config.format is supported on Bedrock
+      supportsNativeStructuredOutput: true,
```
[the remark this answers is not in the document]
Comment (muraliavarma) [reply packages/amazon-bedrock/src/anthropic/bedrock-anthropic-provider.ts:323]: The structured-outputs-2025-11-13 beta header is only required by the direct Anthropic API, not by Bedrock. Structured outputs are GA on Bedrock and work without any beta header.
                                                                                                                                                                                                
From the https://docs.aws.amazon.com/bedrock/latest/userguide/structured-output.html:        

Structured outputs is generally available in all commercial AWS regions for the select Amazon Bedrock serverless models.

The official Bedrock example uses output_config.format with no anthropic_beta in the request body:
```json
  {
    "anthropic_version": "bedrock-2023-05-31",
    "messages": [...],
    "max_tokens": 3000,
    "output_config": {
      "format": {
        "type": "json_schema",
        "schema": { ... }
      }
    }
  }
```
The extra anthropic-beta HTTP header that gets sent is harmless because Bedrock ignores unrecognized headers. This matches the behavior confirmed in the https://github.com/vercel/ai/issues/12298,
where @anthropic-ai/bedrock-sdk works with output_config.format and no beta.

**Review by aayush-kapoor — COMMENTED** [review]
thanks! look correct - just making some minor changes and will merge

File: packages/amazon-bedrock/src/bedrock-chat-language-model.test.ts [hunk 2]
```diff
@@ -4327,6 +4327,184 @@ describe('doGenerate', () => {
...
+          properties: {
+            name: { type: 'string' },
+          },
+          required: ['name'],
+        },
+      },
+    });
+  });
+
+  it('should still use json tool fallback for structured output without thinking enabled', async () => {
```
Comment (aayush-kapoor) [inline packages/amazon-bedrock/src/bedrock-chat-language-model.test.ts:4444]: this might need to change eventually. didn't change in this PR since it led to some regression after changed behaviour and would expand the scope of this PR

File: packages/amazon-bedrock/src/bedrock-chat-language-model.ts
Comment (aayush-kapoor) [inline packages/amazon-bedrock/src/bedrock-chat-language-model.ts:1]: change in this file is because bedrock now supports native structured ouptuts. using the falling back to the JSON tool approach was leading to issues when thinking was enabled. so we changed made the guard very specific to that use case for now

**Review by aayush-kapoor — APPROVED** [review]

**Review by dancer — APPROVED** [review]

**Comment by dancer** [comment]
thanks a bunch @muraliavarma 🎉

**Comment by ghost** [comment]
:rocket: Published in:

| Package | Version |
| --- | --- |
| `@ai-sdk/amazon-bedrock` | [`4.0.68`](https://www.npmjs.com/package/%40ai-sdk%2Famazon-bedrock/v/4.0.68) |
| `@ai-sdk/anthropic` | [`3.0.49`](https://www.npmjs.com/package/%40ai-sdk%2Fanthropic/v/3.0.49) |
| `@ai-sdk/google-vertex` | [`4.0.67`](https://www.npmjs.com/package/%40ai-sdk%2Fgoogle-vertex/v/4.0.67) |
