### PR TITLE
fix(ai): remove custom User-Agent header from chat transport

### LINKED ISSUE #9256: Safari User Agent error when sending messages
### Description

In safari, I get this error when sending a message: failed to load resource: request header field User-Agent is not allowed by Access-Control-Allow-Headers.

The user agent header is:
- In safari: `ai-sdk/5.0.53 runtime/browser`
- In chrome: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36`

It seems in Chrome the browser overrides the user-agent header to what it wants it to be. However in Safari it lets it be custom, which is the value that vercel `ai` provides.

I'm curious if this is an issue with just my specific setup with my server/usage. I wonder if https://github.com/vercel/ai-chatbot will run into this issue when it upgrades `ai`. I think the version that introduced the issue is [5.0.43](https://github.com/vercel/ai/blob/main/packages/ai/CHANGELOG.md#5043), but ai-chatbot uses an older version.

My workaround is to delete that header key. I'm already able to do this because I'm overriding the fetch call for useChat:

```ts
useChat({ transport: new DefaultChatTransport({ fetch: async (_, init) => { ... } }) })
```

### AI SDK Version

'ai': 5.0.53
'@ai-sdk/react': 2.0.52

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gr2m**
## Background

Safari and Firefox send the custom `User-Agent` value set by `HttpChatTransport`, which triggers a CORS preflight request. If the user's server doesn't include `User-Agent` in `Access-Control-Allow-Headers`, the request fails with:

> Failed to load resource: Request header field User-Agent is not allowed by Access-Control-Allow-Headers.

Chrome silently drops custom `User-Agent` values (see [Chromium bug #40450316](https://issues.chromium.org/40450316)), masking the issue.

## Summary

- Removed `withUserAgentSuffix` and `getRuntimeEnvironmentUserAgent` from `HttpChatTransport` (`sendMessages` and `reconnectToStream`)
- Provider API calls via `postToApi`/`getFromApi` still set `User-Agent` as before — those requests get sent to the AI Provider API endpoints which support the `User-Agent` header
- Updated tests to remove the user-agent assertions for chat transport

## Manual Verification

Tested with the ai-e2e-next example.

Before

image

After

image

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Related Issues

Fixes #9256

### CODE REVIEW

File: packages/ai/src/ui/http-chat-transport.ts [hunk 1]
```diff
@@ -193,14 +190,10 @@ export abstract class HttpChatTransport<UI_MESSAGE extends UIMessage>
 
     const response = await fetch(api, {
       method: 'POST',
-      headers: withUserAgentSuffix(
-        {
-          'Content-Type': 'application/json',
-          ...headers,
-        },
-        `ai-sdk/${VERSION}`,
-        getRuntimeEnvironmentUserAgent(),
```
Comment (felixarntz) [inline packages/ai/src/ui/http-chat-transport.ts:202]: Was this information used anywhere? I suppose removing it potentially will hinder some tracking or monitoring, or even debugging in case of certain client-side/server-side errors?

Of course fixing the bug is more important, but thought I should ask.

**Review by felixarntz — APPROVED** [review]

File: packages/ai/src/ui/http-chat-transport.ts (hunk 1 above)
Comment (gr2m) [reply packages/ai/src/ui/http-chat-transport.ts:202]: Potentially yes, removing it might cause some friction. I should not have added it to the UI methods in the first place. I only wanted to add it to requests sent to the provider APIs

**Comment by ghost** [comment]
✅ Backport PR created: https://github.com/vercel/ai/pull/13338

**Comment by ghost** [comment]
:rocket: Published in:

| Package | Version |
| --- | --- |
| `ai` | [`7.0.0-beta.13`](https://www.npmjs.com/package/ai/v/7.0.0-beta.13) |
| `@ai-sdk/angular` | [`3.0.0-beta.13`](https://www.npmjs.com/package/%40ai-sdk%2Fangular/v/3.0.0-beta.13) |
| `@ai-sdk/langchain` | [`3.0.0-beta.13`](https://www.npmjs.com/package/%40ai-sdk%2Flangchain/v/3.0.0-beta.13) |
| `@ai-sdk/llamaindex` | [`3.0.0-beta.13`](https://www.npmjs.com/package/%40ai-sdk%2Fllamaindex/v/3.0.0-beta.13) |
| `@ai-sdk/react` | [`4.0.0-beta.13`](https://www.npmjs.com/package/%40ai-sdk%2Freact/v/4.0.0-beta.13) |
| `@ai-sdk/rsc` | [`3.0.0-beta.14`](https://www.npmjs.com/package/%40ai-sdk%2Frsc/v/3.0.0-beta.14) |
| `@ai-sdk/svelte` | [`5.0.0-beta.13`](https://www.npmjs.com/package/%40ai-sdk%2Fsvelte/v/5.0.0-beta.13) |
| `@ai-sdk/vue` | [`4.0.0-beta.13`](https://www.npmjs.com/package/%40ai-sdk%2Fvue/v/4.0.0-beta.13) |
