### PR TITLE
fix(provider/groq): track cached tokens usage

### LINKED ISSUE #8722: Missing `cachedInputTokens` for kimi-k2 on groq
### Description

Was using the new Posthog llm analytics and found out cached tokens are not tracked for kimi k2 on groq. The actual response has the correct usage but ai sdk is not passing that.
https://console.groq.com/docs/prompt-caching#tracking-cache-usage

Probably missing here, will open a PR.

https://github.com/vercel/ai/blob/5c5fab361b8a8392c4d9b6083be67019fff9ec09/packages/groq/src/groq-chat-language-model.ts#L223-L227

### AI SDK Version

 "@ai-sdk/groq": "^2.0.4",
 "ai": "^5.0.28",

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by andrewdoro**
## Background

Groq now supports prompt caching for kimi-k2, we were not tracking this in `usage`.

https://console.groq.com/docs/prompt-caching#tracking-cache-usage

## Summary

Added the correct response format handling for usage.

## Manual Verification

@gr2m verified with example provided by @andrewdoro 

## Tasks

- [X] Tests have been added / updated (for bug fixes / features)
- [X] Documentation has been added / updated (for bug fixes / features)
- [X] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [X] Formatting issues have been fixed (run `pnpm prettier-fix` in the project root)
- [X] I have reviewed this pull request (self-review)

## Related Issues

fixes #8722

### CODE REVIEW

File: packages/groq/src/groq-chat-language-model.ts [hunk 1]
```diff
@@ -224,6 +224,8 @@ export class GroqChatLanguageModel implements LanguageModelV2 {
         inputTokens: response.usage?.prompt_tokens ?? undefined,
         outputTokens: response.usage?.completion_tokens ?? undefined,
         totalTokens: response.usage?.total_tokens ?? undefined,
```
Comment (Radu-Raicea) [inline packages/groq/src/groq-chat-language-model.ts:226]:
```suggestion
        totalTokens: response.usage?.total_tokens ?? undefined,
        reasoningTokens: response.usage?.completion_tokens_details?.reasoning_tokens ?? undefined,
```

**Review by Radu-Raicea — COMMENTED** [review]
Let's add the reasoning tokens too while we're at it :D

File: packages/groq/src/groq-chat-language-model.ts (hunk 1 above)
Comment (gr2m) [reply packages/groq/src/groq-chat-language-model.ts:226]: @Radu-Raicea can you file a separate PR for `reasoningTokens` please?

**Review by gr2m — COMMENTED** [review]
Thank you Andrei, great pull request! 

I tried to verify that it works manually, but am not sure how I can trigger input tokens to be cached?

I tried this

```ts
  const result = await generateText({
    model: groq('moonshotai/kimi-k2-instruct'),
    system: "You are a helpful AI assistant that provides detailed explanations about complex topics. Always provide comprehensive answers with examples and context.",
    prompt: 'What is quantum computing? Explain in 300 words or less',
  });

  console.log(result.text);
  console.log();
  console.log('Token usage:', result.usage);
  console.log('Finish reason:', result.finishReason);

  const messages = [
    ...result.response.messages,
    { role: 'user' as const, content: 'Can you give me an example of a quantum algorithm?' },
  ];

  const followUpResult = await generateText({
    model: groq('moonshotai/kimi-k2-instruct'),
    messages,
  });

  console.log(followUpResult.text);
  console.log();
  console.log('Token usage:', followUpResult.usage);
  console.log('Finish reason:', followUpResult.finishReason);
```

But it ended with

```
Token usage: {
  inputTokens: 350,
  outputTokens: 225,
  totalTokens: 575,
  cachedInputTokens: undefined
}
```

**Comment by andrewdoro** [comment]
Hi @gr2m in your example prompt caching won't work as groq only catches the longest prefix.

So in your example your first generation context system + prompt, while the second one has a totally different prefix (results from first + different user message)

[Caching Requirements](https://console.groq.com/docs/prompt-caching#caching-requirements)
Exact Prefix Matching: Cache hits require exact matches of the beginning of your prompt
Minimum Prompt Length: The minimum cacheable prompt length varies by model, ranging from 128 to 1024 tokens depending on the specific model used.


Check this example from groq. You can see how initial messages are continuously used for generations.
```tsx
import Groq from "groq-sdk";

const groq = new Groq();

async function multiTurnConversation() {
  // Initial conversation with system message and first user input
  const initialMessages = [
    {
      role: "system",
      content: "You are a helpful AI assistant that provides detailed explanations about complex topics. Always provide comprehensive answers with examples and context."
    },
    {
      role: "user",
      content: "What is quantum computing?"
    }
  ];

  // First request - creates cache for system message
  const firstResponse = await groq.chat.completions.create({
    messages: initialMessages,
    model: "moonshotai/kimi-k2-instruct-0905"
  });

  console.log("First response:", firstResponse.choices[0].message.content);
  console.log("Usage:", firstResponse.usage);

  // Continue conversation - system message and previous context will be cached
  const conversationMessages = [
    ...initialMessages,
    firstResponse.choices[0].message,
    {
      role: "user",
      content: "Can you give me a simple example of how quantum superposition works?"
    }
  ];

  const secondResponse = await groq.chat.completions.create({
    messages: conversationMessages,
    model: "moonshotai/kimi-k2-instruct-0905"
  });

  console.log("Second response:", secondResponse.choices[0].message.content);
  console.log("Usage:", secondResponse.usage);

  // Continue with third turn
  const thirdTurnMessages = [
    ...conversationMessages,
    secondResponse.choices[0].message,
    {
      role: "user",
      content: "How does this relate to quantum entanglement?"
    }
  ];

  const thirdResponse = await groq.chat.completions.create({
    messages: thirdTurnMessages,
    model: "moonshotai/kimi-k2-instruct-0905"
  });

  console.log("Third response:", thirdResponse.choices[0].message.content);
  console.log("Usage:", thirdResponse.usage);
}

multiTurnConversation().catch(console.error);
```

**Comment by gr2m** [comment]
I tried to replicate the example from groq, not sure what I missed? Can you help update my example above so we can test your PR end-to-end?

**Comment by andrewdoro** [comment]
sure rn

**Comment by andrewdoro** [comment]
try this a couple of times


```tsx 
const initialMessages = [
    {
      role: 'system',
      content:
        'You are a helpful AI assistant that provides detailed explanations about complex topics. Always provide comprehensive answers with examples and context.',
    },
    {
      role: 'user',
      content: 'What is quantum computing? Explain in 300 words or less',
    },
  ] as ModelMessage[];

  const result = await generateText({
    model: groq('moonshotai/kimi-k2-instruct'),
    messages: initialMessages,
  });

  console.log(result.text);
  console.log();
  console.log('Token usage:', result.usage);
  console.log('Finish reason:', result.finishReason);

  const followUpMessages = [
    ...initialMessages,
    ...result.response.messages,
    {
      role: 'user' as const,
      content: 'Can you give me an example of a quantum algorithm?',
    },
  ];

  const followUpResult = await generateText({
    model: groq('moonshotai/kimi-k2-instruct'),
    messages: followUpMessages,
  });

  console.log(followUpResult.text);
  console.log();
  console.log('Token usage:', followUpResult.usage);
  console.log('Finish reason:', followUpResult.finishReason);
```

**Comment by andrewdoro** [comment]
the thing was in always passing the intial messages, for the prefix to be the same

**Comment by gr2m** [comment]
that worked, thank you!

**Review by gr2m — APPROVED** [review]
Congrats on your first PR to the AI SDK and thank you for contributing 🖤
