### PR TITLE
fix(provider/google): preserve thoughtSignature through tool execution

### LINKED ISSUE #10344: Gemini 3: Function call is missing a thought_signature in functionCall parts
### Description

Seems to be related to https://github.com/vercel/ai/issues/8379

With gemini 3, I'm observing the same behavior: Errors in function call output result in bricked context.

Image

Image

### AI SDK Version

"ai": "^5.0.80",
"@ai-sdk/google": "^2.0.34",

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dancer**
## Background

gemini 3 pro returns thoughtSignatures with tool calls to maintain reasoning context across multi-turn conversations. when tool execution failed, these signatures were not preserved, causing subsequent turns to fail with 400 errors from google

## Summary

- added providerMetadata preservation in tool execution (error and success cases)
- added providerMetadata field to tool-error type
- updated response message conversion to include providerOptions from tool results
- updated google provider type definitions and conversion logic

## Manual Verification

created comprehensive integration test in `examples/ai-core/src/agent/google-multiturn-tool-error.ts`
- tool call with error (turn 1) preserves signature
- multi-turn conversation with error history works (turn 2)
- successful tool call preserves signature (turn 3)
- raw chunks show google sends signatures

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Related issues

Fixes https://github.com/vercel/ai/issues/10344

### CODE REVIEW

File: packages/ai/src/generate-text/execute-tool-call.ts [hunk 1]
```diff
@@ -75,6 +75,7 @@ export async function executeToolCall<TOOLS extends ToolSet>({
               type: 'tool-result',
               output: part.output,
               preliminary: true,
+              providerMetadata: toolCall.providerMetadata,
```
Comment (gr2m) [inline packages/ai/src/generate-text/execute-tool-call.ts]: this line should not be necessary since the `...toolCall` spread in L74

**Review by gr2m — COMMENTED** [review]
🚀

**Review by gr2m — APPROVED** [review]

**Comment by ghost** [comment]
⚠️ Backport to release-v5.0 created but has conflicts: https://github.com/vercel/ai/pull/10377

**Comment by eddieconk** [comment]
@gr2m will this backport to the google vertex provider as well? Seeing a similar issue there even after updating to `ai@5.0.96`

**Comment by nauxliu** [comment]
I'm still encountering the issue with ai@5.0.97. I suspect this is because I'm using the Vercel AI Gateway and need to wait for Vercel to upgrade it. Could you confirm?

**Comment by gr2m** [comment]
> I'm still encountering the issue with ai@5.0.97. I suspect this is because I'm using the Vercel AI Gateway and need to wait for Vercel to upgrade it. Could you confirm?

Yes, but gateway should be working now as well.

**Comment by ItayElgazar** [comment]
I'm running into this issue with Vertex, is this fixed on Vertex too?

**Comment by eddieconk** [comment]
@gr2m I think I've repro'd the issue in vertex and provided a new issue here: https://github.com/vercel/ai/issues/10560
