### PR TITLE
fix (provider/openai): default strict mode to false

### LINKED ISSUE #6913: V5 - Tool execute() won't infer zod schema parameters
### Description

Setting up zod.object as the tool parameters result in error in the execute function.

Image

Image

also at runtime, Im getting this error back from openAI 

```
"data":{"error":{"message":"Invalid schema for function 'getAvailableTimeSlots': schema must be a JSON Schema of 'type: \"object\"', got 'type: \"None\"'.","type":"invalid_request_error","param":"tools[0].parameters","code":"invalid_function_parameters"}}}}}
```

EDIT: figured out that in V5 the **parameters** property was replaced with **inputSchema** (is that correct?)

### AI SDK Version

- ai: 5.0.0.beta-2
- @ai-sdk/openai: 2.0.0-beta.2
- @ai-sdk/react: 2.0.0-beta.2

### PR DESCRIPTION
**Pull request by lgrammel**
## Background

In AI SDK 5, strict mode for tool calling and output generation was enabled by default for the OpenAI responses and chat language models.

However, this caused several issues, e.g. #6913 #6642 #4662

## Summary

* default strict mode to false for openai responses and chat language models (breaking change)
* introduce provider option `strictJsonSchema` for chat language models
* rename provider option `strictSchemas` to `strictJsonSchema` for responses language model (breaking change)

## Related Issues

Fixes #6913 #6642 #4662

### CODE REVIEW

**Comment by BajekekButLost** [comment]
is there any way to set strict mode to false on the latest stable version?

File: packages/openai/src/openai-chat-options.ts [hunk 1]
```diff
@@ -118,6 +118,13 @@ export const openaiProviderOptions = z.object({
    * @default 'auto'
    */
   serviceTier: z.enum(['auto', 'flex']).optional(),
+
+  /**
+   * Whether to use strict JSON schema validation.
+   *
+   * @default true
```
Comment (shaper) [inline packages/openai/src/openai-chat-options.ts:125]: Is this accurate? The rest of the PR seems to be the opposite.

Comment (lgrammel) [reply packages/openai/src/openai-chat-options.ts:125]: no needs updating good catch
