### PR TITLE
fix(mcp): prevent prototype pollution by using secureJsonParse

### LINKED ISSUE #14309: [Security] MCP transports use raw JSON.parse + mergeObjects prototype pollution
## Summary
Two prototype pollution vectors:

### 1. MCP Transports Use Raw JSON.parse (Medium)
All MCP transport files use native `JSON.parse()` instead of the SDK's own `secureJsonParse()`. MCP transports parse data from external, untrusted MCP servers.
**Files:** `packages/mcp/src/tool/mcp-http-transport.ts`, `mcp-sse-transport.ts`, `mcp-stdio-transport.ts`, `oauth.ts`
**Fix:** Replace with `secureJsonParse()` already available in the codebase.

### 2. mergeObjects Missing Proto Filter (Medium-High)
`packages/ai/src/util/merge-objects.ts` deep merges without filtering `__proto__`, `constructor`, or `prototype`. Called from `process-ui-message-stream.ts:334` where `messageMetadata` from SSE chunks is merged.
**Fix:** Filter dangerous keys in `mergeObjects()`.

## Impact
Crafted MCP server responses or SSE chunks could achieve prototype pollution.

### PR DESCRIPTION
**Pull request by aayush-kapoor**
## Background

alternate to https://github.com/vercel/ai/pull/14313

Prototype pollution vulnerabilities exist in MCP transports and mergeObjects. MCP transports use raw JSON.parse() on data from untrusted MCP servers, and mergeObjects deep-merges without filtering dangerous keys like __proto__, constructor, or prototype. See https://github.com/vercel/ai/issues/14309.

## Summary

- replace `JSON.parse()` with `secureJsonParse()`
- skip __proto__, constructor, and prototype keys during the merge loop

## Manual Verification

na

## Checklist

- [x] All commits are signed (PRs with unsigned commits cannot be merged)
- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Related Issues

fixes #14309

### CODE REVIEW

**Comment by aayush-kapoor** [comment]
@lgrammel re your comment here https://github.com/vercel/ai/pull/14313#discussion_r3079996403, i think `secureJsonParse` is the correct way to go

parseJSON is async and the code lines that need the changes have synchronous signatures (`deserializeMessage`) which we would then have to change. and then all the call sites will have to be awaited.

**Comment by lgrammel** [comment]
@aayush-kapoor my main concern is `secureJsonParse` becoming part of the semi-public api surface of `provider-utils`. If we want to go that route, I would recommend renaming it, e.g. to `secureParseJSON` so it aligns more with our naming schemes.

**Review by lgrammel — APPROVED** [review]

**Review by lgrammel — APPROVED** [review]

File: packages/mcp/src/tool/json-rpc-message.ts [hunk 1]
```diff
@@ -59,3 +61,17 @@ export const JSONRPCMessageSchema = z.union([
...
+
+export async function parseJSONRPCMessage(
+  text: string,
+): Promise<JSONRPCMessage> {
+  try {
+    return JSONRPCMessageSchema.parse(await parseJSON({ text }));
+  } catch (error) {
+    if (JSONParseError.isInstance(error) && error.cause != null) {
+      throw error.cause;
+    }
```
Comment (lgrammel) [inline packages/mcp/src/tool/json-rpc-message.ts]: why is the unwrapping needed?

File: packages/mcp/src/tool/oauth.ts [hunk 2]
```diff
@@ -591,16 +592,22 @@ export async function parseErrorResponse(
...
     const errorClass = OAUTH_ERRORS[error] || ServerError;
     return new errorClass({
       message: error_description || '',
       cause: error_uri,
     });
   } catch (error) {
+    const cause =
+      JSONParseError.isInstance(error) && error.cause != null
+        ? error.cause
+        : error;
```
Comment (lgrammel) [inline packages/mcp/src/tool/oauth.ts]: why is this needed?

Comment (aayush-kapoor) [reply packages/mcp/src/tool/oauth.ts]: actually these were added to preserve the error structure observed when using secureJsonParse. and the only affected snapshots are the new ones added. 

so will revert them

**Review by lgrammel — APPROVED** [review]
