### PR TITLE
fix(xai): add missing stream response schema and provider tool name parsing

### LINKED ISSUE #11492: Can't use any provider-defined tools with xAI
### Description

AI SDK Warning (xai.chat / grok-4): The feature "provider-defined tool code_execution" is not supported.

```ts
import { xai } from "@ai-sdk/xai";
import { streamText } from "ai";

const response = streamText({
  model: xai.responses("grok-4"),
  prompt:
    "Call the web_search tool with the query 'What is the capital of France?'",
  tools: {
    web_search: xai.tools.webSearch(),
    code_execution: xai.tools.codeExecution(),
  },
});

for await (const chunk of response.fullStream) {
  console.dir(chunk, { depth: null });
}
```

### AI SDK Version

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aayush-kapoor**
## Background

The xAI provider tools had some missing schemas and improper mapping of the tool calls in the SDK.
Although these didn't lead to any program from stopping from execution, they weren't consistent with the design of the AISDK and led to error messages in the stream and responses

Reproduce the errors by running the static examples on main and check the logs

Depending on logs of the user, this should fix #11492 

## Summary

- schema for handling streaming parts changed
- proper tool name mapping

## Manual Verification

- verified by running the static example `‎examples/ai-core/src/generate-text/xai-code-execution.ts‎` and ‎`examples/ai-core/src/stream-text/xai-code-execution.ts‎`
- no UI example exists for this at the moment

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

### CODE REVIEW

File: packages/xai/src/responses/xai-responses-api.ts
Comment (aayush-kapoor) [inline packages/xai/src/responses/xai-responses-api.ts:1]: these changes were needed so that on running `examples/ai-core/src/stream-text/xai-code-execution.ts`, we don't get an error message like 
```
[
  {
    "code": "invalid_value",
    "values": [
      "response.done"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid input: expected \"response.done\""
  },
  {
    "expected": "object",
    "code": "invalid_type",
    "path": [
      "response"
    ],
    "message": "Invalid input: expected object, received undefined"
  }
],
```

File: packages/xai/src/responses/xai-responses-language-model.ts [hunk 1]
```diff
@@ -202,11 +202,21 @@ export class XaiResponsesLanguageModel implements LanguageModelV3 {
...
+          xSearchSubTools.includes(part.name ?? '') ||
+          part.type === 'x_search_call'
+        ) {
           toolName = xSearchToolName ?? 'x_search';
-        } else if (part.name === 'code_execution') {
+        } else if (
+          part.name === 'code_execution' ||
+          part.type === 'code_interpreter_call' ||
+          part.type === 'code_execution_call'
+        ) {
```
Comment (aayush-kapoor) [inline packages/xai/src/responses/xai-responses-language-model.ts:219]: all these changes were done so that we don't get a `NoSuchToolError [AI_NoSuchToolError]: Model tried to call unavailable tool` error; the mapping wasn't proper

**Review by lgrammel — APPROVED** [review]

**Comment by ghost** [comment]
✅ Backport PR created: https://github.com/vercel/ai/pull/11662
