### PR TITLE
fix(codemod): remove generateText codemod

### LINKED ISSUE #8298: codemod: `response.text` becomes `response.text.text`
### Description

Reported by @MohtashamMurshid via https://x.com/mohtashamdotdev/status/1960360048703557830 - thanks!

Next step is to create a minimal reproducible test case

### AI SDK Version

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by imranbarbhuiya**
## Background

As mentioned in https://github.com/vercel/ai/pull/8338#issuecomment-3231916006, this is an invalid codemod as `generateText.text` is a string and doesn't need `.text` in it. Not sure if it was meant for any other function but cant find any docs on such change so created this pr to remove the codemod

## Summary

Removed an invalid codemod

## Tasks

- [x] Tests have been added / updated (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] Formatting issues have been fixed (run `pnpm prettier-fix` in the project root)
- [x] I have reviewed this pull request (self-review)

## Related Issues

towards #6552
closes #8398
closes #8298

### CODE REVIEW

File: packages/codemod/scripts/generate-readme.ts [hunk 1]
```diff
@@ -16,13 +16,12 @@ function scanCodemodsRecursively(dir: string, prefix: string = ''): string[] {
     const itemPath = path.join(dir, item);
     const stat = fs.statSync(itemPath);
 
-    if (stat.isDirectory() && item !== 'lib') {
+    if (stat.isDirectory() && item !== 'not-implemented' && item !== 'lib') {
```
Comment (gr2m) [inline packages/codemod/scripts/generate-readme.ts:19]: closes https://github.com/vercel/ai/pull/8398 - thanks!

**Review by gr2m — APPROVED** [review]
Thanks so much for taking care of this 🖤
