### PR TITLE
fix(ai): throw timeout error when streamText times out

### LINKED ISSUE #11577: streamText should throw timeout when timeout occurs (throws NoOutputGeneratedError)
### Description

Follow up from #11571

### PR DESCRIPTION
**Pull request by shubham-021**
## Background

When streamText times out before generating any output, it throws a generic NoOutputGeneratedError with the message "No output generated. Check the stream for errors.". It should throw NoOutputGeneratedError with a proper timeout message and cause.

## Summary

When abort occurs, the abort reason is used as error. It can be an `AbortError` or a `TimeoutError` (or a custom reason object).

## Manual Verification

- [x] run `examples/ai-core/src/stream-text/openai-timeout.ts` and verify output

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Related Issues

fixes #11577

### CODE REVIEW

**Comment by lgrammel** [comment]
Thanks! The behavior should match `generateText`:

```ts
❯ pnpm tsx src/generate-text/openai-timeout
DOMException [TimeoutError]: The operation was aborted due to timeout
```

You can verify by running 

```ts
~/repositories/ai/examples/ai-core main *46 ··································· 11:08:57
❯ pnpm tsx src/stream-text/openai-timeout
```

File: packages/ai/src/generate-text/stream-text.ts
Comment (lgrammel) [inline packages/ai/src/generate-text/stream-text.ts]: this can be simplified by setting `error` using a ternary:

```
const error = abortSignal?.aborted &&
              abortSignal.reason?.name === 'TimeoutError'
? abortSignal.reason : new NoOutputGeneratedError...
```

**Comment by shubham-021** [comment]
> Thanks! The behavior should match `generateText`:
> 
> ```ts
> ❯ pnpm tsx src/generate-text/openai-timeout
> DOMException [TimeoutError]: The operation was aborted due to timeout
> ```
> 
> You can verify by running
> 
> ```ts
> ~/repositories/ai/examples/ai-core main *46 ··································· 11:08:57
> ❯ pnpm tsx src/stream-text/openai-timeout
> ```

I think this well aligned now

```console
pnpm tsx src/stream-text/openai-timeout
DOMException [TimeoutError]: The operation was aborted due to timeout
```

File: packages/ai/src/generate-text/stream-text.ts
Comment (shubham-021) [reply packages/ai/src/generate-text/stream-text.ts]: yeah , you are right , i went with what came first to me , on it

File: packages/ai/src/generate-text/stream-text.test.ts [hunk 1]
```diff
@@ -10109,6 +10109,34 @@ describe('streamText', () => {
       expect(receivedAbortSignal).toBeUndefined();
     });
 
+    it('should throw Timeout error when timeout occurs', async () => {
+      const result = streamText({
+        model: new MockLanguageModelV3({
+          doStream: async () => {
+            // Simulate a model response that takes longer than the timeout
+            await new Promise(r => setTimeout(r, 100));
```
Comment (lgrammel) [inline packages/ai/src/generate-text/stream-text.test.ts]: using timeouts in tests is not recommended. it slows down test exection.

can this be solved with fake timers (vi faketimers)?

Comment (shubham-021) [reply packages/ai/src/generate-text/stream-text.test.ts]: i tried using faketimer , but it is not simulating the blocker perfectly , giving test timeout. 
Can you help me here , what i initially thought was we can plant a promise inside doStream method which doesnt resolve and then advance the timer with more than timeout time , but that gives a test timeout.

**Review by lgrammel — APPROVED** [review]
