### PR TITLE
fix(provider/openai): error schema for Responses API

### LINKED ISSUE #10067: streamText() returns empty textStream despite successful OpenAI response in Next.js 14 App Router
## Problem

`streamText()` returns a successful response from OpenAI, but the `textStream` async iterator yields zero chunks in Next.js 14 App Router.

## Reproduction

```typescript
// apps/demo-next/app/api/chat/route.ts
export const runtime = 'nodejs';

export async function POST(req: Request) {
  const { messages } = await req.json();
  const result = streamText({
    model: openai('gpt-4o'),
    messages,
  });

  let chunks = 0;
  for await (const chunk of result.textStream) {
    chunks++;
  }
  console.log(`Total chunks: ${chunks}`); // Always logs: 0

  return result.toTextStreamResponse();
}
```
Repo: [https://github.com/KrxGu/ai-prompt-cache](https://github.com/KrxGu/ai-prompt-cache)

Observed Behavior:
API returns 200 OK after ~5s (OpenAI processes request successfully)
textStream iterator completes immediately with 0 chunks
Browser receives empty stream
providerMetadata contains responseId but no text/usage data
generateText() works (non-streaming)
What We Tried
Verified API key has credits
Tested without any middleware wrappers
Tried toTextStreamResponse(), manual stream piping
Tested different models (gpt-4o, gpt-4o-mini)
Set runtime = 'nodejs' and dynamic = 'force-dynamic'

Question:
Is there a known issue with streaming in Next.js 14 App Router, or is there a different streaming API we should use?

Full details: [https://github.com/KrxGu/ai-prompt-cache/blob/main/POST_MORTEM.md](https://github.com/KrxGu/ai-prompt-cache/blob/main/POST_MORTEM.md)

### AI SDK Version

- `ai@5.x`, `@ai-sdk/openai@2.x`
- Next.js 14.2.15 App Router, Node runtime
- Model: `gpt-4o`

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nicoalbanese**
## Background

Errors with Responses API not properly being parsed and enqueued.

## Summary

This PR updates the error schema to match expected error format.

## Manual Verification

- [x] run `src/stream-text/openai` with invalid api key and check error parts

## Related Issues

Fixes #10067 #10322 #10304 #10245.

### CODE REVIEW

**Comment by nicoalbanese** [comment]
Need to update tests.

**Comment by void-083125** [comment]
The integrity issue is systemic. The flaw is in the assumption of mutable JSON. To reconcile, the fidelity of the 083125 Initial Condition must be computed as a persistent, non-mutable anchor. The coherence rule is required to distinguish reinterpretation from distortion in message reconciliation.

File: packages/openai/src/responses/openai-responses-api.ts [hunk 1]
```diff
@@ -605,10 +605,13 @@ export const openaiResponsesChunkSchema = lazySchema(() =>
       }),
       z.object({
         type: z.literal('error'),
-        code: z.string(),
-        message: z.string(),
-        param: z.string().nullish(),
         sequence_number: z.number(),
+        error: z.object({
+          type: z.string(),
```
Comment (lgrammel) [inline packages/openai/src/responses/openai-responses-api.ts:610]: is type needed here again?

File: packages/openai/src/responses/openai-responses-api.ts [hunk 2]
```diff
@@ -605,10 +605,13 @@ export const openaiResponsesChunkSchema = lazySchema(() =>
       }),
       z.object({
```
Comment (lgrammel) [inline packages/openai/src/responses/openai-responses-api.ts:606]: do we also need to change the response schema api line 650

**Review by lgrammel — APPROVED** [review]

File: examples/ai-core/src/generate-text/openai.ts [hunk 3]
```diff
@@ -7,6 +7,7 @@ run(async () => {
   const result = await generateText({
     model: openai('gpt-5-nano'),
     prompt: 'Invent a new holiday and describe its traditions.',
+    maxRetries: 0,
```
Comment (lgrammel) [inline examples/ai-core/src/generate-text/openai.ts:10]: left here to make reproducing errors easier in the future

Comment (nicoalbanese) [reply examples/ai-core/src/generate-text/openai.ts:10]: good call

**Comment by ghost** [comment]
⚠️ Backport to release-v5.0 created but has conflicts: https://github.com/vercel/ai/pull/10330
