### PR TITLE
fix(provider/openai): do not set `response_format` to `verbose_json` if model is `gpt-4o-transcribe`

### LINKED ISSUE #8214: response_format set to verbose_json in provider/openai causes gpt-4o-transcribe being unusable
### Description

In PR #8011, response_format is always set to verbose_json

causing the following error

`response_format 'verbose_json' is not compatible with model 'gpt-4o-transcribe'. Use 'json' or 'text' instead.`

### AI SDK Version

"@ai-sdk/openai": "^2.0.19",
"ai": "^5.0.21",

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gr2m**
## Background

As of #8011, `response_format` was always set to `verbose_json` if `providerOptions.openai` is truthy, causing the following error

> response_format 'verbose_json' is not compatible with model 'gpt-4o-transcribe'. Use 'json' or 'text' instead.

## Summary

_TBD_

## Manual Verification

```ts
import { readFile } from 'node:fs/promises';

import { openai } from '@ai-sdk/openai';
import { experimental_transcribe as transcribe } from 'ai';

import 'dotenv/config';

async function main() {
  const result = await transcribe({
    model: openai.transcription('gpt-4o-transcribe'),
    audio: await readFile('data/galileo.mp3'),
    providerOptions: {
      openai: {
        timestampGranularities: ['word']
      }
    }
  });
}

main().catch(console.error);
```

## Tasks

- [x] Tests have been added / updated (for bug fixes / features)
- [x] n/a ~~Documentation has been added / updated (for bug fixes / features)~~
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] Formatting issues have been fixed (run `pnpm prettier-fix` in the project root)
- [ ] I have reviewed this pull request (self-review)
- [x] Investigate impact on [timestamp_granularities](https://platform.openai.com/docs/api-reference/audio/createTranscription#audio_createtranscription-timestamp_granularities_) ("`response_format` must be set to `verbose_json`")

## Related Issues

closes #8214

### CODE REVIEW

**Comment by gr2m** [comment]
> * [ ]  Investigate impact on [timestamp_granularities](https://platform.openai.com/docs/api-reference/audio/createTranscription#audio_createtranscription-timestamp_granularities_) ("`response_format` must be set to `verbose_json`")

It seems that the API does not through an error if `timestamp_granularities` is set if `response_format` is not set to `verbose_json`, but it seems to ignore it. No segments are returned. There is a potential for confusion but I would not introduce a behavior in the SDK that is different from the API.

File: packages/openai/src/transcription/openai-transcription-model.ts [hunk 1]
```diff
@@ -137,7 +137,14 @@ export class OpenAITranscriptionModel implements TranscriptionModelV2 {
...
         prompt: openAIOptions.prompt,
-        response_format: 'verbose_json', // always use verbose_json to get segments
+        // https://platform.openai.com/docs/api-reference/audio/createTranscription#audio_createtranscription-response_format
+        // prefer verbose_json to get segments for models that support it
+        response_format: [
+          'gpt-4o-transcribe',
+          'gpt-4o-mini-transcribe',
+        ].includes(this.modelId)
+          ? 'json'
+          : 'verbose_json',
```
Comment (gr2m) [inline packages/openai/src/transcription/openai-transcription-model.ts:147]: should we support setting `.providerOptions.openai.responseFormat`? There are a few other options
(except for the two specific models 👆🏼 )

Image

Comment (lgrammel) [reply packages/openai/src/transcription/openai-transcription-model.ts:147]: no, it would break our output parsing and would not provide additional data that can be used in our apis afaik

**Review by lgrammel — APPROVED** [review]
