### PR TITLE
fix(ai): fix auto-complete on provider registry and custom provider

### LINKED ISSUE #14780: Provider Registry typeahead for models stopped working
[packages/ai/src/registry/provider-registry.ts](https://github.com/vercel/ai/blob/f04adcbc168424a5c0179a2c7364ef45c730d137/packages/ai/src/registry/provider-registry.ts)

This worked before and is broken now. Add type tests to avoid future regressions

### PR DESCRIPTION
**Pull request by lgrammel**
## Background

Autocomplete on the provider registry stopped working. Most likely caused by the changes in #13001

## Summary

* restored auto-complete functionality
* add type tests
* add support of all model versions incl. string to CustomProvider

## Manual Verification

Check auto-completes and errors in:

- [x] `examples/ai-functions/src/registry/setup-registry.ts`

## Related Issues

Fixes #14780

### CODE REVIEW

File: packages/ai/src/registry/custom-provider.ts [hunk 1]
```diff
@@ -105,24 +91,36 @@ export function customProvider<
...
-  const resolvedFiles = files ?? fallbackProvider?.files?.();
-  const resolvedSkills = skills ?? fallbackProvider?.skills?.();
-
-  return {
+} & (NonNullable<FILES> extends FilesV4
+    ? { files(): FilesV4 }
+    : { files?(): FilesV4 }) &
+  (NonNullable<SKILLS> extends SkillsV4
+    ? { skills(): SkillsV4 }
+    : { skills?(): SkillsV4 }) {
```
Comment (felixarntz) [inline packages/ai/src/registry/custom-provider.ts]: The `NonNullable` statements here are in a way problematic, because they break what originally worked in my implementation: when there's no `files` / `skills` respectively provided, the returned custom provider will have the corresponding property optional. Because here we make them non nullable, the `undefined` case is effectively dropped, making this I believe pointless (it'll always evaluate to having the `files` / `skills` property set for sure (even if that's not actually true).

Now, to be fair, I am now also realizing my original implementation was flawed too: it didn't consider `fallbackProvider`. Ideally, we would want `files` / `skills` to always be defined if either `FILES` / `SKILLS` is provided _or_ if the `fallbackProvider` has them defined. I'm not entirely sure whether that's possible in TypeScript though.

Comment (felixarntz) [reply packages/ai/src/registry/custom-provider.ts]: I attempted to fix this in https://github.com/vercel/ai/pull/14811/changes/d172f227a9be8f808ee0d9e3a32ccf76e2870430, looks like it's working as expected now. Let me know what you think.

You can see the behavior by adjusting e.g. `examples/ai-functions/src/registry/upload-file-custom-provider.ts`:
- e.g. remove the `files` entry, see a type error
- then add a `fallbackProvider` with files support, see the type error go away again
- then replace the `fallbackProvider` with a provider without files support, see the type error reappear

**Review by felixarntz — APPROVED** [review]
lgtm, verified that autocomplete is working again. I pushed one extra commit for your consideration (see other comment)

File: packages/ai/src/util/index.ts [hunk 2]
```diff
@@ -4,6 +4,7 @@ export { cosineSimilarity } from './cosine-similarity';
 export { createDownload } from './download/create-download';
 export { getTextFromDataUrl } from './data-url';
 export type { DeepPartial } from './deep-partial';
+export type { ExtractLiteralUnion } from './extract-literal-union';
```
Comment (lgrammel) [inline packages/ai/src/util/index.ts:7]: ugh this should not have been exposed
