### PR TITLE
fix(openai-compat): decode base64 string data

### LINKED ISSUE #12965: Messages with type: 'file' and mime type: text/... are encoded incorrectly by the OpenAI Compatible provider
### Description

When sending messages of { type: 'file', mediaType: 'text/plain', data: '....string of base 64 encoded data...' } using generateText or streamText, the base 64 encoded string is passed verbatim to the OpenAI Compatible API, inside a {"type":"text","text":"...base 64 encoded data..."} message. Passing the data as base64 is correct when the message to the server is inside a type: 'file' message, but is incorrect when the message to the server is type: 'text'

This contradicts the documentation, which indicates that the data field in FilePart messages is supposed to be a base64 encoded string, as seen here:
https://ai-sdk.dev/docs/reference/ai-sdk-core/generate-text#messages.user-model-message.content.file-part

The incorrect code is on line 122 of this file:
https://github.com/vercel/ai/blob/ed17fe86d13bed87a21dc0264178bd2417f999ce/packages/openai-compatible/src/chat/convert-to-openai-compatible-chat-messages.ts

The textContent should be Base64 decoded when using type: 'text' messages

### AI SDK Version

Latest Git

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aayush-kapoor**
## Background

reported in issue #12965

we decoded the base64 data properly in the anthropic provider but not in openai-compat

## Summary

- added `convertBase64ToUint8Array` to properly decode the string before converting to text
- replaced `Buffer.from(data, 'base64').toString('utf-8')` with the edge-runtime-safe equivalent using `convertBase64ToUint8Array`

## Manual Verification

na

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Related Issues

fixes #12965

### CODE REVIEW

File: packages/anthropic/src/convert-to-anthropic-messages-prompt.ts [hunk 1]
```diff
@@ -31,7 +32,7 @@ import { webSearch_20250305OutputSchema } from './tool/web-search_20250305';
 
 function convertToString(data: LanguageModelV3DataContent): string {
   if (typeof data === 'string') {
-    return Buffer.from(data, 'base64').toString('utf-8');
+    return new TextDecoder().decode(convertBase64ToUint8Array(data));
```
Comment (aayush-kapoor) [inline packages/anthropic/src/convert-to-anthropic-messages-prompt.ts:35]: it's a refactor so doesn't need any test changes and existing tests should pass

**Review by felixarntz — COMMENTED** [review]
@aayush-kapoor 
> we decoded the base64 data properly in the anthropic provider but not in openai-compat

the only production code change here is in the Anthropic provider - that seems to conflict with your statement? or maybe I'm misunderstanding?

**Comment by aayush-kapoor** [comment]
> the only production code change here is in the Anthropic provider - that seems to conflict with your statement? or maybe I'm misunderstanding?

im not sure i understand? what i meant was - previously, decoding was done for properly in anthropic provider but we missed to do it in openai compat. the current change in [packages/anthropic/src/convert-to-anthropic-messages-prompt.ts](https://github.com/vercel/ai/pull/13006/files/170797a4478eb28a4b34bd15881a72c037d98c8a#diff-fc9fe6860029cf7d2b29bf6db0ac2b28a141bc79748a390fb51242198302d4bb) is only to ensure we don't use a node specific api for this

**Review by felixarntz — APPROVED** [review]
@aayush-kapoor ah my bad. I didn't actually see the OpenAI compatible non-test code change before 🤦‍♂️

All good!
