### PR TITLE
fix(vertex/anthropic): passing beta header only for structured outputs

### LINKED ISSUE #10981: Vertex: Unexpected value(s) `structured-outputs-2025-11-13` for the `anthropic-beta` header
### Description

Vertex AI does currently not support the `structured-outputs-2025-11-13` for the `anthropic-beta` header when using sonnet-4.5 in vertex. 

Reproducible example: 
```
import { createVertexAnthropic } from "ai-sdk-anthropic"
import {  generateText, } from "ai"

export const vertexAnthropic = createVertexAnthropic({
    project: "project-id",
    location: "europe-west1", 
    googleAuthOptions: {
        credentials: credentials ,
    },
})

export const test = async () => {
    const res = await generateText({
        model: vertexAnthropic("claude-sonnet-4-5@20250929"),
        messages: [
            {
                role: "user",
                content: "Say hi!",
            },
        ],
    })
    console.log(res)
}
```

### AI SDK Version

- ai@6.0.0-beta.138
- @ai-sdk/google-vertex@4.0.0-beta.102/anthropic

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aayush-kapoor**
## Background

Currently, the vertex anthropic provider only checked the model ID and would pass the beta header for all models that allow structured outputs.

But vertex doesn't yet support passing these beta headers. So we would get an [error like this](https://github.com/vercel/ai/issues/10981) even for a simple generateText function

This PR also addresses a bug when strict mode is enabled and the header is passed (shouldn't happen)

## Summary

- only pass the beta header when actually using native output format and when using strict tools

## Manual Verification

the example `google-vertex-anthropic-sonnet-4-5.ts` was used to verify the fix (was failing before)

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)

## Future Work

ideally, we handle this shortcoming in our implementation of vertex provider
- if beta header is to be passed, we intercept it and then we could pass a providerOption saying `structuredOutputMode: 'jsonTool'` (continued in this PR after the comment https://github.com/vercel/ai/pull/11015#issuecomment-3634356904)

## Related Issues

Fixes #10981

### CODE REVIEW

**Comment by aayush-kapoor** [comment]
all the commits till here fix the original issue. 

commits after this point are to account for the change in example `/examples/ai-core/src/generate-object/google-vertex-anthropic.ts` which fails in the current flow

that example will fail and give an error. but to enable it for users who want to use the latest anthropic models with vertex, we force the use of JSON tool

File: examples/ai-core/src/generate-object/google-vertex-anthropic-sonnet-4-5.ts
Comment (aayush-kapoor) [inline examples/ai-core/src/generate-object/google-vertex-anthropic-sonnet-4-5.ts:1]: was failing before fix

File: examples/ai-core/src/generate-object/google-vertex-anthropic.ts
Comment (aayush-kapoor) [inline examples/ai-core/src/generate-object/google-vertex-anthropic.ts:1]: this file (after changing the model ID) was failing even after the prev fix was applied)

File: packages/anthropic/src/anthropic-messages-language-model.test.ts [hunk 1]
```diff
@@ -2335,7 +2529,7 @@ describe('AnthropicMessagesLanguageModel', () => {
         it('should include advanced-tool-use beta header', async () => {
           expect(server.calls[0].requestHeaders).toMatchInlineSnapshot(`
             {
-              "anthropic-beta": "structured-outputs-2025-11-13,advanced-tool-use-2025-11-20",
+              "anthropic-beta": "advanced-tool-use-2025-11-20",
```
Comment (lgrammel) [inline packages/anthropic/src/anthropic-messages-language-model.test.ts]: why is this dropped?

File: packages/anthropic/src/anthropic-messages-language-model.test.ts [hunk 2]
```diff
@@ -2441,7 +2635,7 @@ describe('AnthropicMessagesLanguageModel', () => {
...
```
Comment (lgrammel) [inline packages/anthropic/src/anthropic-messages-language-model.test.ts]: why is this dropped?

File: examples/ai-core/src/generate-object/google-vertex-anthropic-sonnet-4-5.ts [hunk 3]
```diff
@@ -0,0 +1,18 @@
+import 'dotenv/config';
+import { vertexAnthropic } from '@ai-sdk/google-vertex/anthropic';
+import { generateText } from 'ai';
+import { z } from 'zod';
+
+async function main() {
```
Comment (lgrammel) [inline examples/ai-core/src/generate-object/google-vertex-anthropic-sonnet-4-5.ts]: use `run`

**Review by lgrammel — COMMENTED** [review]
code looks good but test changes indicate a regression might have been introduced

File: packages/anthropic/src/anthropic-messages-language-model.test.ts (hunk 1 above)
Comment (aayush-kapoor) [reply packages/anthropic/src/anthropic-messages-language-model.test.ts]: expected behaviour actually - if this header is passed in vertex provider, it throws an error saying "Unexpected value(s) structured-outputs-2025-11-13 for the anthropic-beta header"

the PR added conditions so that this header isn't passed for functions that don't need it

File: packages/anthropic/src/anthropic-messages-language-model.test.ts (hunk 2 above)
Comment (aayush-kapoor) [reply packages/anthropic/src/anthropic-messages-language-model.test.ts]: same as above, expected behaviour

File: examples/ai-core/src/generate-object/google-vertex-anthropic-sonnet-4-5.ts (hunk 3 above)
Comment (aayush-kapoor) [reply examples/ai-core/src/generate-object/google-vertex-anthropic-sonnet-4-5.ts]: actually will be removing this example - only for testing

**Comment by aayush-kapoor** [comment]
> code looks good but test changes indicate a regression might have been introduced

expected behaviour, see comment above!

File: .changeset/lemon-sheep-behave.md
Comment (gr2m) [inline .changeset/lemon-sheep-behave.md:1]: why two changeset files?

**Review by gr2m — APPROVED** [review]
code changes look good but haven't tested end-to-end, I assume you did

File: .changeset/lemon-sheep-behave.md
Comment (aayush-kapoor) [reply .changeset/lemon-sheep-behave.md:1]: will merge into one - created while iterating

**Comment by aayush-kapoor** [comment]
> code changes look good but haven't tested end-to-end, I assume you did

not with UI example (there isn't one for vertex or structured outputs) but yes, tested with different variations of examples (passing tools, tools + object output)

File: packages/anthropic/src/anthropic-messages-language-model.ts [hunk 4]
```diff
@@ -477,7 +486,13 @@ export class AnthropicMessagesLanguageModel implements LanguageModelV3 {
     }
 
     // structured output:
-    if (useStructuredOutput) {
+    // Only pass beta when actually using native output_format
+    const usingNativeOutputFormat =
+      useStructuredOutput &&
+      responseFormat?.type === 'json' &&
+      responseFormat.schema != null;
```
Comment (lgrammel) [inline packages/anthropic/src/anthropic-messages-language-model.ts:493]: why is this additional condition needed?

**Comment by lgrammel** [comment]
This also seems to fix a bug around strict mode and setting the header. Can this either be separated out into a different PR or added to the description?

**Review by lgrammel — APPROVED** [review]

**Comment by aayush-kapoor** [comment]
> This also seems to fix a bug around strict mode and setting the header. Can this either be separated out into a different PR or added to the description?

EDIT: added in the description

File: packages/anthropic/src/anthropic-messages-language-model.ts (hunk 4 above)
Comment (aayush-kapoor) [reply packages/anthropic/src/anthropic-messages-language-model.ts:493]: just as an extra check - to completely rule out header being sent for functions that don't need it. otherwise it could send it for simple text gen too. i verified with expected behaviour for approx 6 different cases (combinations essentially)

**Comment by AVtheking** [comment]
@aayush-kapoor why it is required to send the structured output header when strict mode is off ?
