### PR TITLE
fix(xai): responses model fixes

### LINKED ISSUE #10491: xai: support grok-code-fast-1 reasoning and associated provider options
### Description

Using the recently backported from v6 xai responses api based language model with xai's `grok-code-fast-1` model specifically produces type validation errors around reasonin like (excerpt):

```
{
  cause: [
    {
      code: 'invalid_union',
      errors: [Array],
      path: [],
      message: 'Invalid input'
    }
  ],
  value: {
    sequence_number: 39,
    type: 'response.reasoning_summary_text.delta',
    delta: ' math',
    item_id: 'rs_fbf4ba9f-07b3-110d-0165-503ab01796c6',
    output_index: 0,
    summary_index: 0
  },
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_TypeValidationError)]: true
}
```

sample script: https://gist.github.com/shaper/6d6dc9cce0a89b5ddb1f9ef4d5ca6e52

further, we would want support for ai gateway to set xai's equivalent of `store: false` and to turn on encrypted reasoning. Docs are at https://docs.x.ai/docs/guides/responses-api

Initial review it looks like:
- we need a way to add `include: ["reasoning.encrypted_content"]` to the request body. OpenAI's responses AI SDK provider has an `include` option for this
- the docs describe a `store_messages` boolean but I am not seeing whether that turns into a simple `store` boolean like with OpenAI, or is `store_messages` and where it's passed in the request
- possible additional work required from their docs depending on AI SDK internals, but maybe this is up to the developer?
  - pass back encrypted reasoning in subsequent messages https://docs.x.ai/docs/guides/responses-api#returning-encrypted-thinking-content
  - pass back response ids aka chaining the conversation https://docs.x.ai/docs/guides/responses-api#chaining-the-conversation

### AI SDK Version

- ai: 5.0.99
- @ai-sdk/xai: 2.0.35

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gr2m**
## Background

We introduced `xai.responses()` via #9896. But we ran into various problems with the initial implementation

## Summary

- implement reasoning
- implement `store` and `previousResponseId` provider option
- implement implicit `include: ['reasoning.encrypted_content']`
- fix timestamp meta data

## Manual Verification

Tested with `examples/ai-core/src/stream-text/xai.ts` and `grok-code-fast-1` model and all the different provider options and multiturn requests

<details>
<summary><code>examples/ai-core/src/stream-text/xai.ts</code> (altered)</summary>

```ts
import { xai, XaiResponsesProviderOptions } from '@ai-sdk/xai';
import { streamText } from 'ai';

import { run } from '../lib/run';
import { saveRawChunks } from '../lib/save-raw-chunks';

import 'dotenv/config';

run(async () => {
  const result = await streamText({
    model: xai.responses('grok-code-fast-1'),
    // model: xai.responses('grok-4-fast-reasoning'),
    // model: xai.responses('grok-4-fast-non-reasoning'),
    // model: xai.responses('grok-4-1-fast-reasoning'),
    // model: xai.responses('grok-4-1-fast-non-reasoning'),
    prompt: 'What is specifically notable about the style of Sonoran food?',
    providerOptions: {
      xai: {
        store: false,
      } satisfies XaiResponsesProviderOptions,
    },
  });

  // await saveRawChunks({ result, filename: 'xai-stream-reasoning-store-false' });

  for await (const part of result.fullStream) {
    if (part.type === 'reasoning-delta') {
      process.stdout.write(`\x1b[34m${part.text}\x1b[0m`);
    } else if (part.type === 'text-delta') {
      process.stdout.write(part.text);
    }
  }

  console.log();
  console.log('Token usage:', await result.usage);
  console.log('Finish reason:', await result.finishReason);
  console.log(
    'Provider metadata:',
    JSON.stringify(await result.providerMetadata, null, 2),
  );
});
```

</details>

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Future Work

- Implement `encrypted_content` for multi-turn chat with reasoning models and `store: false`

## Related Issues

fixes #10491

### CODE REVIEW

File: packages/xai/src/get-response-metadata.ts [hunk 1]
```diff
@@ -2,14 +2,21 @@ export function getResponseMetadata({
   id,
   model,
   created,
+  created_at,
 }: {
   id?: string | undefined | null;
   created?: number | undefined | null;
+  created_at?: number | undefined | null;
```
Comment (gr2m) [inline packages/xai/src/get-response-metadata.ts:9]: `POST /v1/chat/completions ` has `{ "created": "..." }`

while

 `POST /v1/responses`  has `{ "created_at": "..." }`

🤷🏼

**Review by dancer — APPROVED** [review]

**Comment by ghost** [comment]
✅ Backport PR created: https://github.com/vercel/ai/pull/10539
