### PR TITLE
fix(xai): update model list - add GA models, remove beta variants

### LINKED ISSUE #13621: 🤖 Provider model changes - xai
**Provider:** `xai`
**Type:** Model list diff

### New models
- `grok-4.20-0309-non-reasoning`
- `grok-4.20-0309-reasoning`
- `grok-4.20-multi-agent-0309`

### Obsolete models
- `grok-4.20-beta-0309-non-reasoning`
- `grok-4.20-beta-0309-reasoning`
- `grok-4.20-multi-agent-beta-0309`

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary
Updates the xai provider model list per #13621. Adds 3 GA model IDs and removes the corresponding beta variants.

## Changes
- Added `grok-4.20-0309-non-reasoning`, `grok-4.20-0309-reasoning`, `grok-4.20-multi-agent-0309` to chat options, responses options, and gateway model settings
- Removed `grok-4.20-multi-agent-beta`, `grok-4.20-non-reasoning-beta`, `grok-4.20-reasoning-beta` from gateway model settings

Fixes #13621

This contribution was developed with AI assistance (Claude Code).

### CODE REVIEW

File: packages/gateway/src/gateway-language-model-settings.ts [hunk 1]
```diff
@@ -161,9 +161,9 @@ export type GatewayModelId =
   | 'xai/grok-4-fast-reasoning'
   | 'xai/grok-4.1-fast-non-reasoning'
   | 'xai/grok-4.1-fast-reasoning'
-  | 'xai/grok-4.20-multi-agent-beta'
-  | 'xai/grok-4.20-non-reasoning-beta'
-  | 'xai/grok-4.20-reasoning-beta'
+  | 'xai/grok-4.20-0309-non-reasoning'
+  | 'xai/grok-4.20-0309-reasoning'
+  | 'xai/grok-4.20-multi-agent-0309'
```
Comment (felixarntz) [inline packages/gateway/src/gateway-language-model-settings.ts]: adjusting this to use the actual model names on AI Gateway:
```suggestion
  | 'xai/grok-4.20-multi-agent'
  | 'xai/grok-4.20-non-reasoning'
  | 'xai/grok-4.20-reasoning'
```

**Review by felixarntz — APPROVED** [review]
@mvanhorn Thanks for the PR, LGTM!

only the AI Gateway model IDs are slightly different, so I'm updating them. Also, this will need a changeset, so I'll add one.

**Comment by ghost** [comment]
✅ Backport PR created: https://github.com/vercel/ai/pull/13769

**Comment by ghost** [comment]
:rocket: Published in:

| Package | Version |
| --- | --- |
| `ai` | [`7.0.0-beta.37`](https://www.npmjs.com/package/ai/v/7.0.0-beta.37) |
| `@ai-sdk/angular` | [`3.0.0-beta.37`](https://www.npmjs.com/package/%40ai-sdk%2Fangular/v/3.0.0-beta.37) |
| `@ai-sdk/gateway` | [`4.0.0-beta.20`](https://www.npmjs.com/package/%40ai-sdk%2Fgateway/v/4.0.0-beta.20) |
| `@ai-sdk/langchain` | [`3.0.0-beta.37`](https://www.npmjs.com/package/%40ai-sdk%2Flangchain/v/3.0.0-beta.37) |
| `@ai-sdk/llamaindex` | [`3.0.0-beta.37`](https://www.npmjs.com/package/%40ai-sdk%2Fllamaindex/v/3.0.0-beta.37) |
| `@ai-sdk/react` | [`4.0.0-beta.37`](https://www.npmjs.com/package/%40ai-sdk%2Freact/v/4.0.0-beta.37) |
| `@ai-sdk/rsc` | [`3.0.0-beta.38`](https://www.npmjs.com/package/%40ai-sdk%2Frsc/v/3.0.0-beta.38) |
| `@ai-sdk/svelte` | [`5.0.0-beta.37`](https://www.npmjs.com/package/%40ai-sdk%2Fsvelte/v/5.0.0-beta.37) |
| `@ai-sdk/vue` | [`4.0.0-beta.37`](https://www.npmjs.com/package/%40ai-sdk%2Fvue/v/4.0.0-beta.37) |
| `@ai-sdk/xai` | [`4.0.0-beta.16`](https://www.npmjs.com/package/%40ai-sdk%2Fxai/v/4.0.0-beta.16) |

**Comment by mvanhorn** [comment]
Thanks for the review and merge, @felixarntz.
