### PR TITLE
Fix/groq reasoning effort enum

### LINKED ISSUE #9791: Loose type definition of reasoningEffort for Groq
### Description

The type definition of `GroqProviderOptions['reasoningEffort']` is way too loose.

https://github.com/vercel/ai/blob/4269a52cd8d8e69e5d4257b12fe26fb6a7914220/packages/groq/src/groq-chat-options.ts#L31

As [official api references](https://console.groq.com/docs/api-reference#chat-create): 

> Allowed values: none, default, low, medium, high

### AI SDK Version

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by priyanshusaini105**
## Background

The GroqProviderOptions['reasoningEffort'] type was previously defined as a loose string with no constraints on accepted values. According to Groq's official API reference, this property should strictly accept only specific values: "none", "default", "low", "medium", or "high". Restricting this to an enum type ensures better type safety and prevents invalid usage.

## Summary

- Updated the Zod schema in `packages/groq/src/groq-chat-options.ts` to use an enum with allowed values, replacing` .string().optional() `with `.enum(["none", "default", "low", "medium", "high"]).optional().`

- This enforces strict validation for the reasoningEffort option and aligns with the Groq API reference.

- Added a patch changeset to document the fix.

## Manual Verification

- Edited the schema and built the package locally to ensure no TypeScript errors.

- Verified that only the accepted enum values are permitted for reasoningEffort, and invalid values are rejected during validation.

- Smoke tested Groq chat options with different allowed values to confirm they are processed correctly.

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)

## Future Work

- Tests can be added to cover type validation for `reasoningEffort `in GroqProviderOptions.

- Further strict typing improvements for provider options.

## Related Issues

Fixes #9791

### CODE REVIEW

File: packages/groq/src/groq-chat-options.ts [hunk 1]
```diff
@@ -28,7 +28,16 @@ export type GroqChatModelId =
...
-  reasoningEffort: z.string().optional(),
+  
+  /**
+   * Specifies the reasoning effort level for model inference.
+   * - 'none': No reasoning
+   * - 'default': Default reasoning level
+   * - 'low': Low reasoning effort
+   * - 'medium': Medium reasoning effort
+   * - 'high': High reasoning effort
+   */
```
Comment (gr2m) [inline packages/groq/src/groq-chat-options.ts:35]:
```suggestion
  /**
   * Specifies the reasoning effort level for model inference.
   * @see https://console.groq.com/docs/reasoning#reasoning-effort
   */
```

**Review by gr2m — APPROVED** [review]
Thanks @priyanshusaini105! Congratulations on your first contribution to the AI SDK 💐

**Comment by priyanshusaini105** [comment]
> Thanks @priyanshusaini105! Congratulations on your first contribution to the AI SDK 💐

Thanks! I am looking for actively contributing to Vercel :)
