### PR TITLE
fix (ai/core): custom env support for stdio MCP transport

### LINKED ISSUE #5258: Can't add env in `experimental_createMCPClient`
### Description

Reproduction steps:

```ts
  const todoistMcpClient = await experimental_createMCPClient({
    transport: {
      type: "stdio",
      command: "npx",
      args: ["-y", "@abhiz123/todoist-mcp-server"],
      env: {
        TODOIST_API_TOKEN: process.env.TODOIST_API_TOKEN!!,
      },
    },
    name: "todoist-mcp",
    onUncaughtError: (error) => {
      console.error(
        "[MCP] Todoist Uncaught error:",
        JSON.stringify(error, null, 2)
      );
    },
  });
```

Error:

[MCP] Todoist Uncaught error: {
  "errno": -2,
  "code": "ENOENT",
  "syscall": "spawn npx",
  "path": "npx",
  "spawnargs": [
    "-y",
    "@abhiz123/todoist-mcp-server"
  ]
}

The other mcp clients work fine if it doesn't need env. Examples:

Image

### Code example

_No response_

### AI provider

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iteratetograceness**
resolves https://github.com/vercel/ai/issues/5258

### CODE REVIEW

**Comment by lgrammel** [comment]
Please add a changeset. Does this require any docs changes?

File: examples/mcp/src/stdio/client.ts [hunk 1]
```diff
@@ -1,19 +1,19 @@
 import { openai } from '@ai-sdk/openai';
 import { experimental_createMCPClient, generateText } from 'ai';
-// import { StdioClientTransport } from 'ai/mcp-stdio';
-import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
```
Comment (lgrammel) [inline examples/mcp/src/stdio/client.ts:4]: on purpose?

File: examples/mcp/src/stdio/client.ts [hunk 2]
```diff
@@ -1,19 +1,19 @@
...
+import { Experimental_StdioMCPTransport as StdioClientTransport } from 'ai/mcp-stdio';
 import 'dotenv/config';
 import { z } from 'zod';
 
 async function main() {
   let mcpClient;
 
   try {
-    // Or use the AI SDK's stdio transport by importing:
-    // import { StdioClientTransport } from 'ai/mcp-stdio';
```
Comment (lgrammel) [inline examples/mcp/src/stdio/client.ts:13]: on purpose?

File: packages/ai/mcp-stdio/create-child-process.ts [hunk 3]
```diff
@@ -33,7 +33,7 @@ function getDefaultEnvironment(): Record<string, string> {
         ]
       : ['HOME', 'LOGNAME', 'PATH', 'SHELL', 'TERM', 'USER'];
 
-  const env: Record<string, string> = {};
+  const env: Record<string, string> = customEnv ?? {};
```
Comment (lgrammel) [inline packages/ai/mcp-stdio/create-child-process.ts:37]: how can we test this? e.g. add `export` here and have a separate test file for this part?

File: packages/ai/mcp-stdio/get-environment.ts [hunk 4]
```diff
@@ -0,0 +1,37 @@
+export function getEnv(
```
Comment (lgrammel) [inline packages/ai/mcp-stdio/get-environment.ts:1]: rename to `getEnvironment`? (to match file name & prefer full names for the most part)

File: packages/ai/mcp-stdio/get-environment.ts [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+  customEnv?: Record<string, string>,
```
Comment (lgrammel) [inline packages/ai/mcp-stdio/get-environment.ts:2]: wondering how to rename this to make it more clear? also, it might be worth a comment mentioning if it's defaults or overrides.

File: packages/ai/mcp-stdio/get-environment.ts (hunk 4 above)
Comment (lgrammel) [reply packages/ai/mcp-stdio/get-environment.ts:1]: or rename file to `get-env.ts`?

**Review by lgrammel — APPROVED** [review]
