### PR TITLE
fix(package/ai): bind functions for v2 -> v3 adapter

### LINKED ISSUE #9093: TypeError: stepModel.doStream is not a function
### Description

```
TypeError: stepModel.doStream is not a function
    at fn (/Users/namitchadha/astral/www/node_modules/ai/src/generate-text/stream-text.ts:1162:43)
    at <anonymous> (/Users/namitchadha/astral/www/node_modules/ai/src/telemetry/record-span.ts:18:28)
    at Object.startActiveSpan (/Users/namitchadha/astral/www/node_modules/ai/src/telemetry/noop-tracer.ts:21:14)
    at recordSpan (/Users/namitchadha/astral/www/node_modules/ai/src/telemetry/record-span.ts:16:17)
    at <anonymous> (/Users/namitchadha/astral/www/node_modules/ai/src/generate-text/stream-text.ts:1114:13)
    at _retryWithExponentialBackoff (/Users/namitchadha/astral/www/node_modules/ai/src/util/retry-with-exponential-backoff.ts:96:18)
    at <anonymous> (/Users/namitchadha/astral/www/node_modules/ai/src/util/retry-with-exponential-backoff.ts:73:5)
    at streamStep (/Users/namitchadha/astral/www/node_modules/ai/src/generate-text/stream-text.ts:1113:21)
    at async fn (/Users/namitchadha/astral/www/node_modules/ai/src/generate-text/stream-text.ts:1535:9)
    at async <anonymous> (/Users/namitchadha/astral/www/node_modules/ai/src/telemetry/record-span.ts:18:22)
```

Code to repro
```ts
  const modelProvider = anthropic('claude-opus-4-20250514');

    const agent = new Agent({
      model: modelProvider,
      system: 'You are a helpful AI assistant with access to web search and webpage content retrieval.',
      tools: {
        webSearch: webSearchTool,
        visitWebpage: visitWebpageTool,
      },
      stopWhen: stepCountIs(10),
    });

    console.log('Agent created successfully');
    console.log('Starting streaming...\n');
    console.log('='.repeat(50));
    console.log('Response:');
    console.log('='.repeat(50));

    const stream = agent.stream({
      messages: [
        {
          role: 'user',
          content: 'What is the capital of France? use web search',
        },
      ],
    });

    let fullText = '';
    let chunkCount = 0;

    for await (const chunk of stream.textStream) {
      chunkCount++;
      process.stdout.write(chunk);
      fullText += chunk;
    }
```

### AI SDK Version

        "ai": "^5.1.0-beta.19",
        "@ai-sdk/anthropic": "^2.0.22",
        "@ai-sdk/openai": "^2.0.42",

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aayush-kapoor**
## Background

Current implementation of v2 -> v3 adapters doesn't bind the functions properly and just changes the specification version, leading to an error seen in #9093 

## Summary

explicitly bind the functions for each respective models

## Manual Verification

Verified the bug goes away by small reproduction of the error in `examples/repro-issue-9093` after this change

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] Formatting issues have been fixed (run `pnpm prettier-fix` in the project root)

## Related Issues

Fixes #9093

### CODE REVIEW

File: examples/repro-issue-9093/9093-repro.ts [hunk 1]
```diff
@@ -0,0 +1,51 @@
+import { anthropic } from '@ai-sdk/anthropic';
+import { Agent, stepCountIs, tool } from 'ai';
+import 'dotenv/config';
+import { z } from 'zod';
+
+async function main() {
```
Comment (lgrammel) [inline examples/repro-issue-9093/9093-repro.ts]: use `run` helper or rm

**Comment by lgrammel** [comment]
Instead of adding an e2e test and a separate pkg, I would prefer unit tests using `MockLanguageModelV2`

**Comment by aayush-kapoor** [comment]
that makes sense, this was just for reproducing in case you wanted to as well. will be removing!

File: packages/ai/src/model/resolve-model.test.ts [hunk 2]
```diff
@@ -21,6 +22,67 @@ describe('resolveLanguageModel', () => {
...
+      await resolvedModel.doGenerate({
+        prompt: [
+          { role: 'user', content: [{ type: 'text', text: 'hello' }] },
+        ],
+      } as any);
+
+      expect(v2.doGenerateCalls.length).toBe(1);
+    });
+
+    it('should bind methods for a plain v2-shaped object', async () => {
```
Comment (aayush-kapoor) [inline packages/ai/src/model/resolve-model.test.ts]: @lgrammel i added this particular test because when simply using `MockLanguageModelV2`, the test case would still pass even if I removed the change in `transformToV3LanguageModel` in `resolve-model.ts`

It might be because of how we define the model in `MockLanguageModelV2`. In any case, this second tests fails if we remove the change in that function

File: packages/ai/src/model/resolve-model.ts [hunk 3]
```diff
@@ -14,6 +14,8 @@ function transformToV3LanguageModel(model: LanguageModelV2): LanguageModelV3 {
   return {
     ...model,
     specificationVersion: 'v3',
+    doGenerate: model.doGenerate.bind(model),
+    doStream: model.doStream.bind(model),
   };
```
Comment (gr2m) [inline packages/ai/src/model/resolve-model.ts]: good catch, I didn't think of that. 

I wonder if we should maybe use a Proxy for the adapters? It might be a good fit for our use case

```ts
return new Proxy(model, {
  get(target, prop) {
    if (prop === 'specificationVersion') {
      return 'v3';
    }
    return target[prop];
  }
});
```

I think it would make it pretty clean to also override the methods, it seems like the right primitive to use here. Let me know what you think!

Comment (aayush-kapoor) [reply packages/ai/src/model/resolve-model.ts]: yup i think that makes sense, changing

**Review by gr2m — APPROVED** [review]
