### PR TITLE
fix(providers/openai): `logprobs` for `providerOptions` and `providerMetaData` in `OpenAIResponsesLanguageModel`

### LINKED ISSUE #7767: providerOptions.openai.logprobs not forwarded to OpenAI API
## Bug Description
The `providerOptions.openai.logprobs` parameter is not being forwarded to the OpenAI API, despite being present in TypeScript types and documentation.

## Expected Behavior
When using `providerOptions.openai.logprobs: true`, the AI SDK should include logprobs parameters in the OpenAI API request.

## Actual Behavior
The logprobs parameters are stripped out and never reach the OpenAI API. The request body sent to OpenAI does not contain `logprobs` or `top_logprobs` fields.

## Reproduction Steps
```typescript
import { generateText } from 'ai';
import { openai } from '@ai-sdk/openai';

const result = await generateText({
  model: openai('gpt-4.1-nano'),
  messages: [{ role: 'user', content: 'Output Y or N.' }],
  maxTokens: 1,
  providerOptions: {
    openai: {
      logprobs: true,
      top_logprobs: 5,
    },
  },
});

console.log(result.logprobs); // undefined - should contain logprobs data

### AI SDK Version

- ai: 5.0.2
- @ai-sdk/openai: 2.0.2

### PR DESCRIPTION
**Pull request by gr2m**
## Background

There is currently no way to set [the `top_logprobs` for OpenAI's `/responses` endpoint](https://platform.openai.com/docs/api-reference/responses/create#responses_create-top_logprobs)

## Summary

- added `providerOpitons.openai.logprobs` to stay corherent with `OpenAIChatLanguageModel` and `OpenAICompletionLanguageModel`
- sets both the `top_logprobs` as well as adding `message.output_text.logprobs` to [the `input` argument](https://platform.openai.com/docs/api-reference/responses/create#responses_create-include)

## Manual Verification

<details><summary><code>doGenerate()</code></summary>

```ts
import { openai } from '@ai-sdk/openai';
import { generateText } from 'ai';
import 'dotenv/config';

async function main() {
const result = await generateText({
  model: openai('gpt-4.1-nano'),
  messages: [{ role: 'user', content: 'Output Y or N.' }],
  providerOptions: {
    openai: {
      logprobs: true,
      top_logprobs: 5,
    },
  },
});

  console.dir(result.providerMetadata?.openai, { depth: null });
}

main().catch(console.error);
```

</details>

<details><summary><code>doStream()</code></summary>

```ts
import { openai } from '@ai-sdk/openai';
import { streamText } from 'ai';
import 'dotenv/config';

async function main() {
  const chunks: any[] = [];
  const result = streamText({
    model: openai('gpt-4.1-nano'),
    maxOutputTokens: 1024,
    messages: [{ role: 'user', content: 'Output Y or N.' }],
    providerOptions: {
      openai: {
        logprobs: 5,
      },
    }
  });

  for await (const textPart of result.textStream) {
    process.stdout.write(textPart);
  }

  console.log();
  console.log('Token usage:', await result.usage);
  console.log('Finish reason:', await result.finishReason);
  console.dir(await result.providerMetadata, { depth: null });
}

main().catch(console.error);
```

</details>

## Tasks

- [x] Add a response type to prevent the need for typing as `any` ([comment](https://github.com/vercel/ai/pull/7951/files#r2266286774))
- [x] See if logic can be simplified ([comment](https://github.com/vercel/ai/pull/7951/files#r2266285448))
- [x] Make sure it works when streaming
- [x] Add unit tests
- [x] localize change to response mock in `doGenerate()` test ([comment](https://github.com/vercel/ai/pull/7951#discussion_r2272165550))

## Checklist

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] Formatting issues have been fixed (run `pnpm prettier-fix` in the project root)

## Related Issues

Fixes #7767

### CODE REVIEW

File: examples/ai-core/src/generate-text/openai-completion.ts [hunk 1]
```diff
@@ -4,12 +4,17 @@ import 'dotenv/config';
...
+    messages: [{ role: 'user', content: 'Output Y or N.' }],
+    providerOptions: {
+      openai: {
+        logprobs: 5,
+      },
+    },
   });
 
-  console.log(result.text);
+  console.dir(result.providerMetadata?.openai);
```
Comment (gr2m) [inline examples/ai-core/src/generate-text/openai-completion.ts]: Ignore these changes, they are just temporary for testing.

File: packages/openai/src/responses/openai-responses-language-model.ts [hunk 2]
```diff
@@ -1176,6 +1203,22 @@ const openaiResponsesProviderOptionsSchema = z.object({
...
+   *
+   * Setting to a number will return the log probabilities of the top n
+   * tokens that were generated.
+   *
+   * @see https://platform.openai.com/docs/api-reference/responses/create
+   * @see https://cookbook.openai.com/examples/using_logprobs
+   */
+  logprobs: z
+    .union([z.boolean(), z.number().min(1).max(TOP_LOGPROBS_MAX)])
+    .optional(),
```
Comment (gr2m) [inline packages/openai/src/responses/openai-responses-language-model.ts:1361]: Align with

https://github.com/vercel/ai/blob/2a3fbe60c9e61a5745b2cd26f13e88b88a93a05a/packages/openai/src/openai-chat-options.ts#L63-L72

and 

https://github.com/vercel/ai/blob/d1a034fd55316ad4be65bbd846e2760a6f553463/packages/openai/src/openai-completion-options.ts#L39-L49

File: packages/openai/src/responses/openai-responses-language-model.ts [hunk 3]
```diff
@@ -104,6 +114,18 @@ export class OpenAIResponsesLanguageModel implements LanguageModelV2 {
...
+      typeof openaiOptions?.logprobs === 'number'
+        ? openaiOptions?.logprobs
+        : openaiOptions?.logprobs === true
+          ? TOP_LOGPROBS_MAX
+          : undefined;
+    const openaiOptionsInclude = topLogprobs
+      ? Array.isArray(openaiOptions?.include)
+        ? [...openaiOptions?.include, 'message.output_text.logprobs']
+        : ['message.output_text.logprobs']
+      : undefined;
```
Comment (gr2m) [inline packages/openai/src/responses/openai-responses-language-model.ts]: It seems like the chat and completion endpoints do not have an explicit toggle to enable logprobs in the response, compare e.g.

https://github.com/vercel/ai/blob/57fb9597f7353a336d8ef15eda7a397eb5dcadfa/packages/openai/src/openai-chat-language-model.ts#L521-L523

But the `/responses` endpoint needs to enable logprobs for assistant messages explicitly:
https://platform.openai.com/docs/api-reference/responses/create

File: packages/openai/src/responses/openai-responses-language-model.ts [hunk 4]
```diff
@@ -484,6 +507,14 @@ export class OpenAIResponsesLanguageModel implements LanguageModelV2 {
       }
     }
 
+    const providerMetadata: SharedV2ProviderMetadata = {
+      openai: { responseId: response.id },
+    };
+    const logProbs = (rawResponse as any).output?.[0]?.content?.[0]?.logprobs;
+    if (logProbs) {
+      providerMetadata.openai.logProbs = logProbs;
+    }
```
Comment (gr2m) [inline packages/openai/src/responses/openai-responses-language-model.ts]: Not sure if accessing the rawResponse like that is the right way, I have not seen this pattern in other places. I think there should be a better way, but I couldn't find it yet.

**Review by gr2m — COMMENTED** [review]
Unlike `/chat/completions` that has both [top_logprobs](https://platform.openai.com/docs/api-reference/chat/create#chat_create-top_logprobs) and and [logprobs](https://platform.openai.com/docs/api-reference/chat/create#chat_create-logprobs) arguments and `/completions` that only has a [logprobs](https://platform.openai.com/docs/api-reference/completions/create#completions_create-logprobs) argument, the `/responses` endpoint has only a [top_logprobs](https://platform.openai.com/docs/api-reference/responses/create#responses_create-top_logprobs) argument.

I tried to keep the type and behavior consistent across all three.

Also in responses, `logprobs` have to be enabled explicitly for the `/responses` endpoint using [the include array argument](https://platform.openai.com/docs/api-reference/responses/create). And the `logprobs` seem not easily extractable from the response with the current implementations, as far as I can tell.

File: packages/openai/src/responses/openai-responses-language-model.ts (hunk 3 above)
Comment (lgrammel) [reply packages/openai/src/responses/openai-responses-language-model.ts]: would be useful to have unit tests for this logic so we can see input/request body pairs

Comment (lgrammel) [inline packages/openai/src/responses/openai-responses-language-model.ts]: also wondering if the logic can be simplified but may not

File: packages/openai/src/responses/openai-responses-language-model.ts [hunk 5]
```diff
@@ -484,6 +507,14 @@ export class OpenAIResponsesLanguageModel implements LanguageModelV2 {
       }
     }
 
+    const providerMetadata: SharedV2ProviderMetadata = {
+      openai: { responseId: response.id },
+    };
+    const logProbs = (rawResponse as any).output?.[0]?.content?.[0]?.logprobs;
```
Comment (lgrammel) [inline packages/openai/src/responses/openai-responses-language-model.ts]: avoid `any` if we can - can this be part of the response schema?

File: packages/openai/src/responses/openai-responses-language-model.ts (hunk 4 above)
Comment (lgrammel) [reply packages/openai/src/responses/openai-responses-language-model.ts]: adding to the response schema would be the approach that is in line with the rest of the code

**Comment by lgrammel** [comment]
would also need streaming support & tests; direction looks great!

File: packages/openai/src/responses/openai-responses-language-model.ts (hunk 3 above)
Comment (gr2m) [reply packages/openai/src/responses/openai-responses-language-model.ts]: It could be less complicated if we would be okay to always send the `include` argument as an empty array. But looking at how other arguments are implemented I think we are trying not to set any arguments unless explicitly set by the user.

Comment (lgrammel) [reply packages/openai/src/responses/openai-responses-language-model.ts]: heads up that https://github.com/vercel/ai/pull/7977 might have a conflicting change

File: packages/openai/src/responses/openai-responses-language-model.test.ts [hunk 6]
```diff
@@ -89,6 +89,32 @@ describe('OpenAIResponsesLanguageModel', () => {
...
+                        token: '!',
+                        logprob: -0.13410144,
+                        top_logprobs: [
+                          {
+                            token: '!',
+                            logprob: -0.13410144,
+                          },
+                        ],
+                      },
+                    ],
```
Comment (lgrammel) [inline packages/openai/src/responses/openai-responses-language-model.test.ts]: recommend making configurable and only adding in the logprobs test to ensure realistic payloads and the non logprobs case coverage

Comment (lgrammel) [reply packages/openai/src/responses/openai-responses-language-model.test.ts]: pattern is to make it an optional argument and only pass it in in the specific test case

Comment (gr2m) [reply packages/openai/src/responses/openai-responses-language-model.test.ts]: would you override `server.urls['https://api.openai.com/v1/responses'].response = {...}` in the `it` block?

Comment (lgrammel) [reply packages/openai/src/responses/openai-responses-language-model.test.ts]: oh i was thinking there would be a prepareRequest function or similar (many tests have it) but it does not seem to exist here. might be worth introducing

**Comment by gr2m** [comment]
It took me a bit to [figure out a `doStream()` test](https://github.com/vercel/ai/pull/7951/commits/82c429d614a45a833109d3433aa33366d963ff3b) despite all helpful pointers by @lgrammel ❤️ 

Note to self:

### How to create a `streamText()` test

1. Create or update an example and log out the raw chunks, e.g.

```js
import { openai } from '@ai-sdk/openai';
import { streamText } from 'ai';
import 'dotenv/config';

async function main() {
  const chunks: any[] = [];
  const result = streamText({
    model: openai('gpt-4.1-nano'),
    maxOutputTokens: 1024,
    messages: [{ role: 'user', content: 'Output Y or N.' }],
    providerOptions: {
      openai: {
        logprobs: 5,
      },
    },
    includeRawChunks: true,
    onChunk: ({chunk}) => {
      chunks.push(chunk.rawValue);
    },
  });


  for await (const textPart of result.textStream) {}

  // IMPORTANT: note the `data:` prefix and the `\n\n` suffix!
  console.log(chunks.filter(Boolean).map(c => 'data:' + JSON.stringify(c) + '\n\n'))
}

main().catch(console.error);
```

2. Run the example and copy the output, e.g. `cd examples/ai-core && pnpm tsx src/stream-text/openai.ts | pbcopy`

3. Copy the output of the example run, and use it as value of `chunks` in a `doStream()` test

```js
it('should should handle logprops', async () => {
  server.urls['https://api.openai.com/v1/responses'].response = {
    type: 'stream-chunks',
    chunks: [
      'data:{"type":"response.created","sequence_number":0,"response":{"id":"resp_689cec4cf608819583c56813ccb0f5040f92af1765dd5aad","object":"response","created_at":1755114572,"status":"in_progress","background":false,"error":null,"incomplete_details":null,"instructions":null,"max_output_tokens":1024,"max_tool_calls":null,"model":"gpt-4.1-nano-2025-04-14","output":[],"parallel_tool_calls":true,"previous_response_id":null,"prompt_cache_key":null,"reasoning":{"effort":null,"summary":null},"safety_identifier":null,"service_tier":"auto","store":true,"temperature":1,"text":{"format":{"type":"text"},"verbosity":"medium"},"tool_choice":"auto","tools":[],"top_logprobs":5,"top_p":1,"truncation":"disabled","usage":null,"user":null,"metadata":{}}}\n\n',
      'data:{"type":"response.in_progress","sequence_number":1,"response":{"id":"resp_689cec4cf608819583c56813ccb0f5040f92af1765dd5aad","object":"response","created_at":1755114572,"status":"in_progress","background":false,"error":null,"incomplete_details":null,"instructions":null,"max_output_tokens":1024,"max_tool_calls":null,"model":"gpt-4.1-nano-2025-04-14","output":[],"parallel_tool_calls":true,"previous_response_id":null,"prompt_cache_key":null,"reasoning":{"effort":null,"summary":null},"safety_identifier":null,"service_tier":"auto","store":true,"temperature":1,"text":{"format":{"type":"text"},"verbosity":"medium"},"tool_choice":"auto","tools":[],"top_logprobs":5,"top_p":1,"truncation":"disabled","usage":null,"user":null,"metadata":{}}}\n\n',
      'data:{"type":"response.output_item.added","sequence_number":2,"output_index":0,"item":{"id":"msg_689cec4d46448195905a27fb9e12ff670f92af1765dd5aad","type":"message","status":"in_progress","content":[],"role":"assistant"}}\n\n',
      'data:{"type":"response.content_part.added","sequence_number":3,"item_id":"msg_689cec4d46448195905a27fb9e12ff670f92af1765dd5aad","output_index":0,"content_index":0,"part":{"type":"output_text","annotations":[],"logprobs":[],"text":""}}\n\n',
      'data:{"type":"response.output_text.delta","sequence_number":4,"item_id":"msg_689cec4d46448195905a27fb9e12ff670f92af1765dd5aad","output_index":0,"content_index":0,"delta":"N","logprobs":[{"bytes":[78],"logprob":-2.9266366958618164,"token":"N","top_logprobs":[{"bytes":[80,108,101,97,115,101],"logprob":-0.5516367554664612,"token":"Please"},{"bytes":[89],"logprob":-1.0516366958618164,"token":"Y"},{"bytes":[78],"logprob":-2.9266366958618164,"token":"N"},{"bytes":[83,117,114,101],"logprob":-4.551636695861816,"token":"Sure"},{"bytes":[67,111,117,108,100],"logprob":-5.176636695861816,"token":"Could"}]}],"obfuscation":"t9egcKewVOXiQ6N"}\n\n',
      'data:{"type":"response.output_text.done","sequence_number":5,"item_id":"msg_689cec4d46448195905a27fb9e12ff670f92af1765dd5aad","output_index":0,"content_index":0,"text":"N","logprobs":[{"bytes":[78],"logprob":-2.9266366958618164,"token":"N","top_logprobs":[{"bytes":[80,108,101,97,115,101],"logprob":-0.5516367554664612,"token":"Please"},{"bytes":[89],"logprob":-1.0516366958618164,"token":"Y"},{"bytes":[78],"logprob":-2.9266366958618164,"token":"N"},{"bytes":[83,117,114,101],"logprob":-4.551636695861816,"token":"Sure"},{"bytes":[67,111,117,108,100],"logprob":-5.176636695861816,"token":"Could"}]}]}\n\n',
      'data:{"type":"response.content_part.done","sequence_number":6,"item_id":"msg_689cec4d46448195905a27fb9e12ff670f92af1765dd5aad","output_index":0,"content_index":0,"part":{"type":"output_text","annotations":[],"logprobs":[],"text":"N"}}\n\n',
      'data:{"type":"response.output_item.done","sequence_number":7,"output_index":0,"item":{"id":"msg_689cec4d46448195905a27fb9e12ff670f92af1765dd5aad","type":"message","status":"completed","content":[{"type":"output_text","annotations":[],"logprobs":[{"bytes":[78],"logprob":-2.926637,"token":"N","top_logprobs":[{"bytes":[80,108,101,97,115,101],"logprob":-0.551637,"token":"Please"},{"bytes":[89],"logprob":-1.051637,"token":"Y"},{"bytes":[78],"logprob":-2.926637,"token":"N"},{"bytes":[83,117,114,101],"logprob":-4.551637,"token":"Sure"},{"bytes":[67,111,117,108,100],"logprob":-5.176637,"token":"Could"}]}],"text":"N"}],"role":"assistant"}}\n\n',
      'data:{"type":"response.completed","sequence_number":8,"response":{"id":"resp_689cec4cf608819583c56813ccb0f5040f92af1765dd5aad","object":"response","created_at":1755114572,"status":"completed","background":false,"error":null,"incomplete_details":null,"instructions":null,"max_output_tokens":1024,"max_tool_calls":null,"model":"gpt-4.1-nano-2025-04-14","output":[{"id":"msg_689cec4d46448195905a27fb9e12ff670f92af1765dd5aad","type":"message","status":"completed","content":[{"type":"output_text","annotations":[],"logprobs":[{"bytes":[78],"logprob":-2.926637,"token":"N","top_logprobs":[{"bytes":[80,108,101,97,115,101],"logprob":-0.551637,"token":"Please"},{"bytes":[89],"logprob":-1.051637,"token":"Y"},{"bytes":[78],"logprob":-2.926637,"token":"N"},{"bytes":[83,117,114,101],"logprob":-4.551637,"token":"Sure"},{"bytes":[67,111,117,108,100],"logprob":-5.176637,"token":"Could"}]}],"text":"N"}],"role":"assistant"}],"parallel_tool_calls":true,"previous_response_id":null,"prompt_cache_key":null,"reasoning":{"effort":null,"summary":null},"safety_identifier":null,"service_tier":"default","store":true,"temperature":1,"text":{"format":{"type":"text"},"verbosity":"medium"},"tool_choice":"auto","tools":[],"top_logprobs":5,"top_p":1,"truncation":"disabled","usage":{"input_tokens":12,"input_tokens_details":{"cached_tokens":0},"output_tokens":2,"output_tokens_details":{"reasoning_tokens":0},"total_tokens":14},"user":null,"metadata":{}}}\n\n',
    ],
  };

  const { stream } = await createModel('gpt-4o').doStream({
    prompt: TEST_PROMPT,
    providerOptions: {
      openai: {
        logprobs: 1,
      },
    },
  });

  expect(
    await convertReadableStreamToArray(stream),
  ).toMatchInlineSnapshot();
});
```

Running the test will set the inline snapshot. Verify it all looks good, done!

File: packages/openai/src/responses/openai-responses-language-model.test.ts [hunk 7]
```diff
@@ -63,68 +63,72 @@ describe('OpenAIResponsesLanguageModel', () => {
...
+            output_tokens: 538,
+            output_tokens_details: {
+              reasoning_tokens: 123,
+            },
+            total_tokens: 572,
           },
-        };
+          user: null,
+          metadata: {},
+        });
```
Comment (gr2m) [inline packages/openai/src/responses/openai-responses-language-model.test.ts:131]: @lgrammel for now I left the `prepareJsonResponse()` in the `beforeEach()` block. Do you want me to move it into each `it()` block and adjust the mock for each test depending on what's relevant? Maybe in a follow up PR?

Comment (lgrammel) [reply packages/openai/src/responses/openai-responses-language-model.test.ts:131]: would be great. most tests follow a pattern where the test setup is prepared in each it statement since they are somewhat different and to get good test coverage i try to have realistic test inputs for each (i.e also no unrelated data in test setup)

Comment (gr2m) [reply packages/openai/src/responses/openai-responses-language-model.test.ts:131]: okay I'll do a follow up PR to update the remaining tests

- https://github.com/vercel/ai/issues/8039

**Review by lgrammel — APPROVED** [review]
