### PR TITLE
fix(providers/xai): return actual usage when streaming instead of NaN

### LINKED ISSUE #5736: `streamText()` returns NaN for usage with @ai-sdk/xai
## Bug description
I encountered an issue while integrating the `xAI Grok provider`. When calling `streamText()`, the returned usage object has promptTokens, completionTokens, and totalTokens all set to `NaN`. Here is my code:
```ts
import { xai } from '@ai-sdk/xai';
import { streamText } from 'ai';

streamText({
    model: xai('grok-3-mini-beta'),
    messages: [{
        role: 'user',
        content: 'who are you'
    }],
    onFinish: async ({ usage }) => {
        console.log('Usage:', usage);
    },
}
```

Returns

``` 
Usage: {promptTokens: NaN, completionTokens: NaN, totalTokens: NaN}
```

## Info about my ai sdk version
```
"ai": "^4.3.5",
"@ai-sdk/xai": "^1.2.11",
```

### PR DESCRIPTION
**Pull request by samdenty**
## Background

To resolve #5736

## Summary

Added support for `includeUsage: boolean` in openai-compatible, and use this new option inside the xai provider to return proper usage instead of NaN numbers

## Tasks

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] If required, a _patch_ changeset for relevant packages has been added
- [x] You've run `pnpm prettier-fix` to fix any formatting issues

### CODE REVIEW

File: packages/openai-compatible/src/openai-compatible-completion-language-model.ts [hunk 1]
```diff
@@ -227,6 +228,12 @@ export class OpenAICompatibleCompletionLanguageModel
     const body = {
       ...args,
       stream: true,
+
+      // only include stream_options when in strict compatibility mode:
+      stream_options:
+        this.config.compatibility === 'strict'
+          ? { include_usage: true }
```
Comment (samdenty) [inline packages/openai-compatible/src/openai-compatible-completion-language-model.ts:235]: added this in case we want to use it in the future

File: packages/openai-compatible/src/openai-compatible-chat-language-model.ts [hunk 2]
```diff
@@ -375,7 +376,17 @@ export class OpenAICompatibleChatLanguageModel implements LanguageModelV1 {
...
+    const body = {
+      ...args,
+      stream: true,
+
+      // only include stream_options when in strict compatibility mode:
+      stream_options:
+        this.config.compatibility === 'strict'
+          ? { include_usage: true }
+          : undefined,
+    };
```
Comment (lgrammel) [inline packages/openai-compatible/src/openai-compatible-chat-language-model.ts:388]: this was openai specific - we need to be more granular for compat providers - e.g. by having a `includeUsage` provider flag that can be enabled for `xai`

Comment (samdenty) [reply packages/openai-compatible/src/openai-compatible-chat-language-model.ts:388]: good idea 👍

File: packages/openai-compatible/src/openai-compatible-chat-language-model.ts [hunk 3]
```diff
@@ -375,7 +376,16 @@ export class OpenAICompatibleChatLanguageModel implements LanguageModelV1 {
...
+    const body = {
+      ...args,
+      stream: true,
+
+      // only include stream_options when in strict compatibility mode:
+      stream_options: this.config.includeUsage
+        ? { include_usage: true }
+        : undefined,
+    };
+
```
Comment (lgrammel) [inline packages/openai-compatible/src/openai-compatible-chat-language-model.ts:388]: might be good to have a test case for this since it might break w/ porting and refactorings

**Review by lgrammel — APPROVED** [review]

File: packages/openai-compatible/src/openai-compatible-chat-language-model.test.ts [hunk 4]
```diff
@@ -646,6 +646,34 @@ describe('doGenerate', () => {
       expect(warnings).toEqual([]);
     });
 
+    it('should respect the includeUsage option', async () => {
+      prepareJsonResponse({ content: '{"value":"Spark"}' });
```
Comment (lgrammel) [inline packages/openai-compatible/src/openai-compatible-chat-language-model.test.ts:650]: contet can be simpler e.g. `'test'`

File: packages/openai-compatible/src/openai-compatible-chat-language-model.ts (hunk 3 above)
Comment (samdenty) [reply packages/openai-compatible/src/openai-compatible-chat-language-model.ts:388]: good idea 🙏

**Review by lgrammel — APPROVED** [review]
